force-app/main/default/objects/Opportunity/fields/Account_Region_Code__c.field-meta.xml
<CustomField>
    <fullName>Account_Region_Code__c</fullName>
    <businessOwnerUser>mmikael.franzen@dllgroup.com.st01d06</businessOwnerUser>
    <description>This field is used to store the Account Region Code. It is used in Delete_NonSynced_quotes Flow to get the opportunities with SE region code. (US - 677478)</description>
    <formula>Account.Account_Region_Code__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>This field is used to store the Account Region Code.</inlineHelpText>
    <label>Account Region Code</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Customer_Id__c.field-meta.xml
<CustomField>
    <fullName>Customer_Id__c</fullName>
    <businessOwnerUser>mmikael.franzen@dllgroup.com.st01d06</businessOwnerUser>
    <description>Customer&apos;s account external identifier. It is used for list view. The text type of the field is selected to search by the value of this field</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Customer&apos;s account external identifier. It is used for list view. The text type of the field is selected to search by the value of this field</inlineHelpText>
    <label>Customer Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Customer_Name__c.field-meta.xml
<CustomField>
    <fullName>Customer_Name__c</fullName>
    <businessOwnerUser>mmikael.franzen@dllgroup.com.st01d06</businessOwnerUser>
    <description>Customer&apos;s account name. It is used for list view. The text type of the field is selected to search by the value of this field</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Customer&apos;s account name</inlineHelpText>
    <label>Customer Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/End_User__c.field-meta.xml
<CustomField>
    <fullName>End_User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Use this field to look up an existing Customer</inlineHelpText>
    <label>End User Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Opportunities (End User)</relationshipLabel>
    <relationshipName>Opportunities_End_User</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/ISO_Code__c.field-meta.xml
<CustomField>
    <fullName>ISO_Code__c</fullName>
    <businessOwnerUser>mmikael.franzen@dllgroup.com.st01d06</businessOwnerUser>
    <description>ISO code of quote for customer</description>
    <formula>TEXT(Account.Region_Relationship__r.ISO_Code__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>ISO code of quote for customer</inlineHelpText>
    <label>ISO Code</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Legal_Entity_Description__c.field-meta.xml
<CustomField>
    <fullName>Legal_Entity_Description__c</fullName>
    <description>Captures the name of the DLL Legal Entity that is the ultimate parent to the operating sales Business Units managing the Opportunity as a text value. Used in Sharing Rules to permit sharing of Opportunities with Users working within the same Legal Entity. Populated by Apex code.</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Legal Entity Description</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Program__c.field-meta.xml
<CustomField>
    <fullName>Program__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Relates an Opportunity to its Program. The Opportunity&apos;s UNQ_Vendor_Program__c value is used to fetch the corresponding Program record by this external ID common to both objects. Populated by Apex code.</description>
    <label>Program</label>
    <referenceTo>Program__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Region__c.field-meta.xml
<CustomField>
    <fullName>Region__c</fullName>
    <label>Region</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Asia Pacific</fullName>
            </value>
            <value>
                <fullName>CEE</fullName>
            </value>
            <value>
                <fullName>Central</fullName>
            </value>
            <value>
                <fullName>Global</fullName>
            </value>
            <value>
                <fullName>Latin America</fullName>
            </value>
            <value>
                <fullName>Midwest</fullName>
            </value>
            <value>
                <fullName>Nordics</fullName>
            </value>
            <value>
                <fullName>North America</fullName>
            </value>
            <value>
                <fullName>Northeast</fullName>
            </value>
            <value>
                <fullName>South</fullName>
            </value>
            <value>
                <fullName>Southeast</fullName>
            </value>
            <value>
                <fullName>West Coast</fullName>
            </value>
            <value>
                <fullName>Western Europe</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Region_Relationship__c.field-meta.xml
<CustomField>
    <fullName>Region_Relationship__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Relates an Opportunity to its Region. Populated via automation.</description>
    <label>Region</label>
    <referenceTo>Region__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/CustomerSetupController.cls
/**
 * This class is used as apex controller for quoteCalculator, customerSearchCmp LWC (Customer screen)
 * 
 * @author Elena Sokolova @date 2020-12-15 
 */
public with sharing class CustomerSetupController {
    
    /**
     * Method is called from LWC to save customer info if where is not such info in the database
     * 
     * @return account Id
     */
    @AuraEnabled
    public static Id saveAccountAndUpdateDeal(String customerInfo, String customerExtId, String quoteId) {
        Account account = new WoSSelector().getAccountByExternalId(customerExtId);

        if (account == null) {
            account = new Account();
        }

        SearchPartyResponseBodyWrapper.Data data = (SearchPartyResponseBodyWrapper.Data) JSON.deserialize(
            customerInfo, 
            SearchPartyResponseBodyWrapper.Data.class
        );

        Quote qoute = new WoSSelector().getQuoteById(quoteId);

        account.RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get(Constants.END_USER_RECORD_TYPE_NAME).getRecordTypeId();
        account.Name = data.name;
        account.External_Identifier__c = customerExtId;
        account.Region_Relationship__c = qoute.Applicable_Offers__r.Offer__r.Program__r.Region__c;
        account.Account_Region_Code__c = qoute.Applicable_Offers__r.Offer__r.Program__r.Region__r.ISO_Code__c;
        account.BillingStreet = data.Address.street;
        account.BillingCity = data.Address.city;
        account.BillingPostalCode = data.Address.postalCode;
        account.Phone = (data.phoneNumbers != null) ? (data.phoneNumbers[0].areaCode + data.phoneNumbers[0].phoneNumber) : '';
        account.Legal_Entity_Name__c = (data.legalEntity != null) ? data.legalEntity.name : null;
        account.Legal_Entity_Description__c = (data.legalEntity != null) ? data.legalEntity.id : null;

        try {
            //upsert account;
            new GenericUtilityClass.WoSDMLProcessor().upsertRecords(new List<SObject>{account});
            updateDeal(quoteId, account.Id, account.Name, customerExtId);
        } catch (Exception e) {
            ErrorLogger errorLog = new ErrorLogger();
            errorLog.logException(e, Constants.GENERIC_ERRORLOG_RECORDTYPE, quoteId, true); 
        }

        
        return account.Id;
    }

    /**
     * Method updates quote status 
     */
    @AuraEnabled
    public static void updateQuoteStatus(String quoteId, String status) {
        Quote qoute = new WoSSelector().getQuoteById(quoteId);
        qoute.Status = status;
        new GenericUtilityClass.WoSDMLProcessor().updateRecords(new List<SObject>{qoute});
        //update qoute;
    }

    /**
     * Method saves customer external id in the opportunity level
     */
    private static void updateDeal(String quoteId, String customerId, String customerName, String customerExtId) {
        Quote qoute = new WoSSelector().getQuoteById(quoteId);
        Opportunity opportunity = new WoSSelector().getOpportunityById(qoute.OpportunityId);
        opportunity.End_User__c = customerId;
        opportunity.Customer_Id__c = customerExtId;
        opportunity.Customer_Name__c = customerName;
        //update opportunity;
        new GenericUtilityClass.WoSDMLProcessor().updateRecords(new List<SObject>{opportunity});
    }


    /**
     * Method gets info about selected customer
     */
    @AuraEnabled
    public static String getCustomerScreenInfo(String quoteId) {
        return JSON.serialize(new WoSSelector().getCustomerScreenInfoByQuoteId(quoteId));
    }

    // inner class-selector
    public without sharing class WoSSelector {

        public Quote getQuoteById(String quoteId) {
            return [
                SELECT  OpportunityId, Status, Auto_Decision__c, Applicable_Offers__r.Offer__r.Program__r.Region__r.ISO_Code__c,
                        Applicable_Offers__r.Offer__r.Program__r.Region__c
                FROM    Quote 
                WHERE   Id = :quoteId
            ];
        }

        private Opportunity getOpportunityById(String opportunityId) {
            return [SELECT End_User__c, Customer_Id__c, Customer_Name__c FROM Opportunity WHERE Id = :opportunityId];
        }

        private Opportunity getCustomerScreenInfoByQuoteId(String quoteId) {
            return [
                SELECT  End_User__c, End_User__r.Name, End_User__r.External_Identifier__c, End_User__r.BillingStreet, 
                        End_User__r.BillingCity, End_User__r.BillingPostalCode,
                        (SELECT Status, Conditions__c, Valid_From__c, Valid_To__c FROM Quotes WHERE Id = :quoteId)
                FROM    Opportunity 
                WHERE   Id IN (SELECT OpportunityId FROM Quote WHERE Id = :quoteId)
            ];
        }

        private Account getAccountByExternalId(String customerExtId) {
            List<Account> accounts = [SELECT Id, Name, External_Identifier__c FROM Account WHERE External_Identifier__c = :customerExtId];
            return (accounts.isEmpty()) ? null : accounts[0];
        }
    }
}