force-app/main/default/objects/Opportunity/fields/Advance_Payments__c.field-meta.xml
<CustomField>
    <fullName>Advance_Payments__c</fullName>
    <description>How many Advance payments made.</description>
    <inlineHelpText>How many Advance payments made or will be made ?</inlineHelpText>
    <label>Advance Payments</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/End_User__c.field-meta.xml
<CustomField>
    <fullName>End_User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Use this field to look up an existing Customer</inlineHelpText>
    <label>End User Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Opportunities (End User)</relationshipLabel>
    <relationshipName>Opportunities_End_User</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/End_User_Phone__c.field-meta.xml
<CustomField>
    <fullName>End_User_Phone__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>End User Phone</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Frequency__c.field-meta.xml
<CustomField>
    <fullName>Frequency__c</fullName>
    <description>Lease terms</description>
    <label>Frequency</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>MONTHLY</fullName>
            </value>
            <value>
                <fullName>ANNUAL</fullName>
            </value>
            <value>
                <fullName>SEMIANNUAL</fullName>
            </value>
            <value>
                <fullName>QUARTERLY</fullName>
            </value>
            <value>
                <fullName>SKIP</fullName>
            </value>
            <value>
                <fullName>UNEQUAL</fullName>
            </value>
            <value>
                <fullName>Semi-Annual</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Interest_Rate__c.field-meta.xml
<CustomField>
    <fullName>Interest_Rate__c</fullName>
    <label>Interest Rate</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Lease_Type__c.field-meta.xml
<CustomField>
    <fullName>Lease_Type__c</fullName>
    <description>Type of Equipment Lease</description>
    <inlineHelpText>Type of Equipment Lease</inlineHelpText>
    <label>Lease Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Fair Market Value ( FMV )</fullName>
            </value>
            <value>
                <fullName>$1 Buy out</fullName>
            </value>
            <value>
                <fullName>FPPO</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Number_of_Assets__c.field-meta.xml
<CustomField>
    <fullName>Number_of_Assets__c</fullName>
    <businessOwnerGroup>Global_Admins</businessOwnerGroup>
    <description>Total number of assets associated with the application. DLL on Demand populates this during quote conversion and it excludes accessories, but does take into account number of units from the quote.</description>
    <inlineHelpText>Total number of assets associated with the application.</inlineHelpText>
    <label>Number of Assets</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Partner_Sales_Rep__c.field-meta.xml
<CustomField>
    <fullName>Partner_Sales_Rep__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup to Contact for Partner Sales Rep Name</description>
    <label>Partner Sales Rep</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Opportunities (Partner Sales Rep)</relationshipLabel>
    <relationshipName>Opportunities1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Payment_Amount__c.field-meta.xml
<CustomField>
    <fullName>Payment_Amount__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Amount of the payment</description>
    <label>Payment Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Rate_Type__c.field-meta.xml
<CustomField>
    <fullName>Rate_Type__c</fullName>
    <description>Rate Type</description>
    <label>Rate Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>LOW RATE</fullName>
            </value>
            <value>
                <fullName>STANDARD RATE</fullName>
            </value>
            <value>
                <fullName>SPECIAL RATE</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Residual_Amount__c.field-meta.xml
<CustomField>
    <fullName>Residual_Amount__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Residual Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Sub_Stage__c.field-meta.xml
<CustomField>
    <fullName>Sub_Stage__c</fullName>
    <description>Opportunity sub stages to be used by each BU</description>
    <label>Sub-Stage</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>StageName</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Warm Leads Identified</fullName>
            </value>
            <value>
                <fullName>On Hold</fullName>
            </value>
            <value>
                <fullName>Prospect</fullName>
            </value>
            <value>
                <fullName>Customer Meeting</fullName>
            </value>
            <value>
                <fullName>Executive Endorsement</fullName>
            </value>
            <value>
                <fullName>Nondisclosure Agreement Executed</fullName>
            </value>
            <value>
                <fullName>Required Functional Approvals Complete (Table 1)</fullName>
            </value>
            <value>
                <fullName>Workshop Hosted</fullName>
            </value>
            <value>
                <fullName>Principles Document/Term Sheet Drafted</fullName>
            </value>
            <value>
                <fullName>Required Functional Approvals Complete (Table 2)</fullName>
            </value>
            <value>
                <fullName>Principles Document/Term Sheet Signed</fullName>
            </value>
            <value>
                <fullName>Program Fact Sheet</fullName>
            </value>
            <value>
                <fullName>Development of Offer</fullName>
            </value>
            <value>
                <fullName>Vendor Risk Application</fullName>
            </value>
            <value>
                <fullName>Determine Risk Acceptance Criteria</fullName>
            </value>
            <value>
                <fullName>ABC Assessment</fullName>
            </value>
            <value>
                <fullName>Remarketing Arrangement</fullName>
            </value>
            <value>
                <fullName>Profit &amp; Loss Calculation</fullName>
            </value>
            <value>
                <fullName>Program Agreement Under Review</fullName>
            </value>
            <value>
                <fullName>DLL Selected</fullName>
            </value>
            <value>
                <fullName>Required Functional Approvals Complete (Table 3)</fullName>
            </value>
            <value>
                <fullName>Local Due Diligence &amp; Approval Committee</fullName>
            </value>
            <value>
                <fullName>Global Credit Committee Approval</fullName>
            </value>
            <value>
                <fullName>Determine Vendor Reporting Requirements</fullName>
            </value>
            <value>
                <fullName>Create Rollout Plan (Global)</fullName>
            </value>
            <value>
                <fullName>Implementation Plan (Local)</fullName>
            </value>
            <value>
                <fullName>Agreement Executed</fullName>
            </value>
            <value>
                <fullName>Assigned Local Implementation</fullName>
            </value>
            <value>
                <fullName>MVP Implemented</fullName>
            </value>
            <value>
                <fullName>Quote Draft</fullName>
            </value>
            <value>
                <fullName>Application Draft</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Term__c.field-meta.xml
<CustomField>
    <fullName>Term__c</fullName>
    <description>NBD</description>
    <label>Term</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Opportunity_Line_Item__c/Opportunity_Line_Item__c.object-meta.xml
<CustomObject>
    <description>Application line items are used in the DLL on Demand partner portal to represent assets and fees tracked during the credit application process. The standard object was not used as products and price books aren&apos;t used in the DoD portal currently.</description>
    <label>Opportunity Line Item</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Line Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Opportunity Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Opportunity_Line_Item__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <businessOwnerGroup>North_America_Admins</businessOwnerGroup>
    <description>The dollar value of the current line item knowing that it will always represent a quantity of one. However not all amounts will roll-up to the total application amount value as some will be pass-through charges.</description>
    <inlineHelpText>The dollar value of the current line item knowing that it will always represent a quantity of one. However not all amounts will roll-up to the total application amount value as some will be pass-through charges.</inlineHelpText>
    <label>Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Opportunity_Line_Item__c/fields/Line_Item_Type__c.field-meta.xml
<CustomField>
    <fullName>Line_Item_Type__c</fullName>
    <businessOwnerGroup>North_America_Admins</businessOwnerGroup>
    <description>The type of line item used to indicate what the item is for and how to use it in calculations.</description>
    <inlineHelpText>The type of line item used to indicate what the item is for and how to use it in calculations.</inlineHelpText>
    <label>Line Item Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Asset</fullName>
            </value>
            <value>
                <fullName>Add-on</fullName>
            </value>
            <value>
                <fullName>Fee</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity_Line_Item__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <businessOwnerGroup>North_America_Admins</businessOwnerGroup>
    <description>The parent opportunity that the line item is for.</description>
    <inlineHelpText>The parent opportunity that the line item is for.</inlineHelpText>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipName>Application_Line_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Opportunity_Line_Item__c/fields/Related_Quote_Line__c.field-meta.xml
<CustomField>
    <fullName>Related_Quote_Line__c</fullName>
    <businessOwnerGroup>North_America_Admins</businessOwnerGroup>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>If the line item was created from a quote, this links to the original quote line item. A series of unique opportunity line items may point to the same quote line item if the quote line item had a quantity greater than one.</description>
    <inlineHelpText>If the line item was created from a quote, this links to the original quote line item. A series of unique opportunity line items may point to the same quote line item if the quote line item had a quantity greater than one.</inlineHelpText>
    <label>Related Quote Line</label>
    <referenceTo>Quote_Line__c</referenceTo>
    <relationshipName>Application_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/creditApplicationOnQuoteHelper.cls
/**
 * Author: Kritika Sharma & Surbhi Goyal: Traction on Demand
 * Date : 24/02/2022.
 */

public class creditApplicationOnQuoteHelper {
    
    // This method performs the primary quote conversion to the credit application.
    public static void updateOpportunityByQuote(List<Quote> quoteList) {
        Set<Id> opportunityIds = new Set<Id>();

        // Get is primary Quote List that's have opportunity
        List<Quote> isPrimaryQuoteList = [
            SELECT Id,
                Advance_Payments__c,
                Amount__c,
                End_User__c,
                Finance_Term_Month__c,
                Interest__c,
                Is_Primary__c,
                Lease_Type__c,
                Opportunity.Advance_Payments__c,
                Opportunity.Amount,
                Opportunity.End_User__c,
                Opportunity.End_User__r.Phone,
                Opportunity.Frequency__c,
                Opportunity.Interest_Rate__c,
                Opportunity.Lease_Type__c,
                Opportunity.Owner.Phone,
                Opportunity.Partner_Sales_Rep__c,
                Opportunity.Payment_Amount__c,
                Opportunity.Rate_Type__c,
                Opportunity.Residual_Amount__c,
                Opportunity.Term__c,
                OpportunityId,
                Partner_Sales_Rep__c,
                Payment_Frequency__c,
                Rate_Type__c,
                Residual__c,
                Term__c,
                Total_Payment__c
            FROM Quote
            WHERE Id In :quoteList
            AND Is_Primary__c = true
            AND OpportunityId != null
            AND Opportunity.Sub_Stage__c = 'Quoting & Proposal'
        ];
        for(Quote quote:isPrimaryQuoteList) {
            opportunityIds.add(quote.OpportunityId);
        }

        // Ensure there are opportunities in this stage before attempting the conversion.
        if(opportunityIds.size() > 0){
            List<Opportunity> opportunityList = [
                    SELECT Id,
                            Advance_Payments__c,
                            End_User__c,
                            Frequency__c,
                            Lease_Type__c,
                            Partner_Sales_Rep__c,
                            Rate_Type__c,
                            Term__c
                    FROM Opportunity
                    WHERE Id In :opportunityIds
            ];

            // Query the assets related to the primary quote (not bulkified, assumes a single quote conversion at a time).
            Map<Id, Decimal> numberOfAssets = new Map<Id, Decimal>();
            List<Quote_Line__c> quoteLines = [
                    SELECT Id,
                            Base_Unit_Sales_Price__c,
                            Equipment_Type__c,
                            Name,
                            Number_of_Units__c
                    FROM Quote_Line__c
                    WHERE Quote__c = :isPrimaryQuoteList[0].Id
            ];

            // Create the list of opportunity lines (again, not bulkified assuming one).
            List<Opportunity_Line_Item__c> oppLines = new List<Opportunity_Line_Item__c>();
            Opportunity_Line_Item__c oppLine = new Opportunity_Line_Item__c();
            Decimal distinctAssets = 0;
            for(Quote_Line__c quoteLine:quoteLines){

                // Tally up the total number of assets considering unit counts.
                if(quoteLine.Equipment_Type__c == 'Asset'){
                    distinctAssets = distinctAssets + quoteLine.Number_of_Units__c;
                }

                // Blow out the number of quote line units into individualized records.
                for(Integer i = 0; i < quoteLine.Number_of_Units__c; i++){
                    oppLine = new Opportunity_Line_Item__c();
                    oppLine.Amount__c = quoteLine.Base_Unit_Sales_Price__c;
                    oppLine.Name = quoteLine.Name;
                    oppLine.Line_Item_Type__c = quoteLine.Equipment_Type__c;
                    oppLine.Opportunity__c = isPrimaryQuoteList[0].OpportunityId;
                    oppLine.Related_Quote_Line__c = quoteLine.Id;
                    oppLines.add(oppLine);
                }
            }
            insert oppLines;
            numberOfAssets.put(isPrimaryQuoteList[0].OpportunityId, distinctAssets);

            // Stamp the values from quote to opportunity
            for(Opportunity opp:opportunityList){
                for(Quote quote : isPrimaryQuoteList) {
                    if(opp.Id == quote.OpportunityId) {
                        if(quote.Advance_Payments__c != null){
                            opp.Advance_Payments__c = decimal.valueof(quote.Advance_Payments__c);
                        }
                        opp.Amount = quote.Amount__c;

                        opp.Frequency__c = quote.Payment_Frequency__c;

                        // Populate a phone number
                        if(quote.Opportunity.End_User__r.Phone != null && quote.Opportunity.End_User__r.Phone != ''){
                            opp.End_User_Phone__c = quote.Opportunity.End_User__r.Phone;
                        } else {
                            opp.End_User_Phone__c = quote.Opportunity.Owner.Phone;
                        }

                        if(quote.Interest__c != null) {
                            opp.Interest_Rate__c = decimal.valueof(quote.Interest__c);
                        }

                        // Transform the lease type label
                        if(quote.Lease_Type__c == 'BO'){
                            opp.Lease_Type__c = label.CREDITAPP_LEASETYPE;
                        } else {
                            opp.Lease_Type__c = quote.Lease_Type__c;
                        }

                        // Stamp the number of assets if it exists.
                        if(numberOfAssets.containsKey(quote.OpportunityId)){
                            opp.Number_of_Assets__c = numberOfAssets.get(quote.OpportunityId);
                        }

                        opp.Partner_Sales_Rep__c = quote.Partner_Sales_Rep__c;
                        opp.Payment_Amount__c = quote.Total_Payment__c;
                        opp.Rate_Type__c = quote.Rate_Type__c;
                        opp.Residual_Amount__c = quote.Residual__c;
                        opp.Sub_Stage__c = 'Application Draft';
                        if(quote.Term__c != null) {
                            opp.Term__c = decimal.valueof(quote.Term__c);
                        }
                    }
                }
            }
            Database.update(opportunityList);
        }
    }
}