force-app/main/default/objects/Opportunity/fields/Application_Date__c.field-meta.xml
<CustomField>
    <fullName>Application_Date__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>This is the date the application is first entered in the source system.</inlineHelpText>
    <label>Application Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Application_Number__c.field-meta.xml
<CustomField>
    <fullName>Application_Number__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <label>Application Number</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Business_Unit1__c.field-meta.xml
<CustomField>
    <fullName>Business_Unit1__c</fullName>
    <defaultValue>$User.Business_Unit_TEXT__c</defaultValue>
    <label>Opportunity Business Unit</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Advanced Solutions</fullName>
            </value>
            <value>
                <fullName>Clean Technology</fullName>
            </value>
            <value>
                <fullName>Commercial Finance</fullName>
            </value>
            <value>
                <fullName>Construction, Transportation &amp; Infrastructure (CTI)</fullName>
            </value>
            <value>
                <fullName>Food &amp; Agriculture (F&amp;A)</fullName>
            </value>
            <value>
                <fullName>Golf and Turf (G&amp;T)</fullName>
            </value>
            <value>
                <fullName>Healthcare</fullName>
            </value>
            <value>
                <fullName>Office Equipment (OE)</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Pay Per Use</fullName>
            </value>
            <value>
                <fullName>Public Finance</fullName>
            </value>
            <value>
                <fullName>Technology Solutions</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Vendor Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Contract__c.field-meta.xml
<CustomField>
    <fullName>Contract__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Relates an Opportunity to its Contract. Lookup populated via Apex code.</description>
    <label>Contract</label>
    <referenceTo>Contract__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/End_User__c.field-meta.xml
<CustomField>
    <fullName>End_User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Use this field to look up an existing Customer</inlineHelpText>
    <label>End User Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Opportunities (End User)</relationshipLabel>
    <relationshipName>Opportunities_End_User</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/End_User_Company_Name__c.field-meta.xml
<CustomField>
    <fullName>End_User_Company_Name__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Use this field when the customer does not exist in Salesforce</inlineHelpText>
    <label>End User Name (Text)</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Sub_Stage__c.field-meta.xml
<CustomField>
    <fullName>Sub_Stage__c</fullName>
    <description>Opportunity sub stages to be used by each BU</description>
    <label>Sub-Stage</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>StageName</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Warm Leads Identified</fullName>
            </value>
            <value>
                <fullName>On Hold</fullName>
            </value>
            <value>
                <fullName>Prospect</fullName>
            </value>
            <value>
                <fullName>Customer Meeting</fullName>
            </value>
            <value>
                <fullName>Executive Endorsement</fullName>
            </value>
            <value>
                <fullName>Nondisclosure Agreement Executed</fullName>
            </value>
            <value>
                <fullName>Required Functional Approvals Complete (Table 1)</fullName>
            </value>
            <value>
                <fullName>Workshop Hosted</fullName>
            </value>
            <value>
                <fullName>Principles Document/Term Sheet Drafted</fullName>
            </value>
            <value>
                <fullName>Required Functional Approvals Complete (Table 2)</fullName>
            </value>
            <value>
                <fullName>Principles Document/Term Sheet Signed</fullName>
            </value>
            <value>
                <fullName>Program Fact Sheet</fullName>
            </value>
            <value>
                <fullName>Development of Offer</fullName>
            </value>
            <value>
                <fullName>Vendor Risk Application</fullName>
            </value>
            <value>
                <fullName>Determine Risk Acceptance Criteria</fullName>
            </value>
            <value>
                <fullName>ABC Assessment</fullName>
            </value>
            <value>
                <fullName>Remarketing Arrangement</fullName>
            </value>
            <value>
                <fullName>Profit &amp; Loss Calculation</fullName>
            </value>
            <value>
                <fullName>Program Agreement Under Review</fullName>
            </value>
            <value>
                <fullName>DLL Selected</fullName>
            </value>
            <value>
                <fullName>Required Functional Approvals Complete (Table 3)</fullName>
            </value>
            <value>
                <fullName>Local Due Diligence &amp; Approval Committee</fullName>
            </value>
            <value>
                <fullName>Global Credit Committee Approval</fullName>
            </value>
            <value>
                <fullName>Determine Vendor Reporting Requirements</fullName>
            </value>
            <value>
                <fullName>Create Rollout Plan (Global)</fullName>
            </value>
            <value>
                <fullName>Implementation Plan (Local)</fullName>
            </value>
            <value>
                <fullName>Agreement Executed</fullName>
            </value>
            <value>
                <fullName>Assigned Local Implementation</fullName>
            </value>
            <value>
                <fullName>MVP Implemented</fullName>
            </value>
            <value>
                <fullName>Quote Draft</fullName>
            </value>
            <value>
                <fullName>Application Approved</fullName>
            </value>
            <value>
                <fullName>Document Request Draft</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/UNQ_Customer__c.field-meta.xml
<CustomField>
    <fullName>UNQ_Customer__c</fullName>
    <description>UNQ Customer ID from external system</description>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <label>UNQ Customer</label>
    <length>125</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/UNQ_Opportunity__c.field-meta.xml
<CustomField>
    <fullName>UNQ_Opportunity__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <label>UNQ Opportunity</label>
    <length>125</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Opportunity/fields/UNQ_Program__c.field-meta.xml
<CustomField>
    <fullName>UNQ_Program__c</fullName>
    <description>Unique ID for the Opportunity&apos;s Program. Set via integration.</description>
    <encryptionScheme>None</encryptionScheme>
    <label>UNQ Program</label>
    <length>125</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/UNQ_Vendor__c.field-meta.xml
<CustomField>
    <fullName>UNQ_Vendor__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>UNQ_Vendor</label>
    <length>125</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity_Line_Item__c/Opportunity_Line_Item__c.object-meta.xml
<CustomObject>
    <description>Application line items are used in the DLL on Demand partner portal to represent assets and fees tracked during the credit application process. The standard object was not used as products and price books aren&apos;t used in the DoD portal currently.</description>
    <label>Opportunity Line Item</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Line Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Opportunity Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Opportunity_Line_Item__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <businessOwnerGroup>North_America_Admins</businessOwnerGroup>
    <description>The dollar value of the current line item knowing that it will always represent a quantity of one. However not all amounts will roll-up to the total application amount value as some will be pass-through charges.</description>
    <inlineHelpText>The dollar value of the current line item knowing that it will always represent a quantity of one. However not all amounts will roll-up to the total application amount value as some will be pass-through charges.</inlineHelpText>
    <label>Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Opportunity_Line_Item__c/fields/Line_Item_Type__c.field-meta.xml
<CustomField>
    <fullName>Line_Item_Type__c</fullName>
    <businessOwnerGroup>North_America_Admins</businessOwnerGroup>
    <description>The type of line item used to indicate what the item is for and how to use it in calculations.</description>
    <inlineHelpText>The type of line item used to indicate what the item is for and how to use it in calculations.</inlineHelpText>
    <label>Line Item Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Asset</fullName>
            </value>
            <value>
                <fullName>Add-on</fullName>
            </value>
            <value>
                <fullName>Fee</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity_Line_Item__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <businessOwnerGroup>North_America_Admins</businessOwnerGroup>
    <description>The parent opportunity that the line item is for.</description>
    <inlineHelpText>The parent opportunity that the line item is for.</inlineHelpText>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipName>Application_Line_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Opportunity_Line_Item__c/fields/Planned_Install_City__c.field-meta.xml
<CustomField>
    <fullName>Planned_Install_City__c</fullName>
    <businessOwnerGroup>North_America_Admins</businessOwnerGroup>
    <description>The city the asset is expected to be delivered to.</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>The city the asset is expected to be delivered to.</inlineHelpText>
    <label>Planned Install City</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity_Line_Item__c/fields/Planned_Install_State__c.field-meta.xml
<CustomField>
    <fullName>Planned_Install_State__c</fullName>
    <businessOwnerGroup>North_America_Admins</businessOwnerGroup>
    <description>The state the asset is expected to be delivered to.</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>The state the asset is expected to be delivered to.</inlineHelpText>
    <label>Planned Install State</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity_Line_Item__c/fields/Planned_Install_Street__c.field-meta.xml
<CustomField>
    <fullName>Planned_Install_Street__c</fullName>
    <businessOwnerGroup>North_America_Admins</businessOwnerGroup>
    <description>The street address the asset is expected to be delivered to.</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>The street address the asset is expected to be delivered to.</inlineHelpText>
    <label>Planned Install Street</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity_Line_Item__c/fields/Planned_ZIP_Code__c.field-meta.xml
<CustomField>
    <fullName>Planned_ZIP_Code__c</fullName>
    <businessOwnerGroup>North_America_Admins</businessOwnerGroup>
    <description>The postal/zip code the asset is expected to be delivered to.</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>The postal/zip code the asset is expected to be delivered to.</inlineHelpText>
    <label>Planned ZIP Code</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/EnrollControllerTest.cls
/**
 * @description       : Apex Test class for Enrolment.
 * @author            : Kritika Sharma : Traction on Demand
 * @last modified on  : 04-07-2022
 * @last modified by  : Kritika Sharma
 **/

@isTest
public with sharing class EnrollControllerTest {

@testSetup static void setup() {

	Account at =new Account();
	at.Name='Service';
	insert at;

	contact ct =new contact();
	ct.LastName='Niranjan';
	ct.AccountId=at.id;
	ct.Email='hans.vedo@dllgroup.com';
	insert ct;

	Opportunity opp1= new Opportunity();
	opp1.application_number__c='A1';
	opp1.Type='Overline';
	opp1.Name='Service';
	opp1.StageName='Closed Won';
	opp1.Accountid=at.id;
	opp1.Contact__c=ct.id;
	opp1.CloseDate=system.today()+1;
	opp1.Amount=11.0;
	opp1.End_User__c=at.id;
	opp1.End_User_Company_Name__c = 'DANIEL INC.';
	opp1.Business_Unit1__c='Digital Imaging';
	opp1.Sub_Stage__c = 'Application Approved';
	opp1.Application_Date__c=system.today().addMonths(-3);
	opp1.UNQ_Customer__c='A1';
	opp1.UNQ_Vendor__c='A1';
	opp1.UNQ_Opportunity__c='A1';
	insert opp1;

	// Contact Role
	OpportunityContactRole cr = new OpportunityContactRole();
	cr.OpportunityId = opp1.Id;
	cr.ContactId = ct.Id;
	cr.Role = 'Signer';
	insert cr;

	cr = new OpportunityContactRole();
	cr.OpportunityId = opp1.Id;
	cr.ContactId = ct.Id;
	cr.Role = 'Billing Contact';
	insert cr;

	cr = new OpportunityContactRole();
	cr.OpportunityId = opp1.Id;
	cr.ContactId = ct.Id;
	cr.Role = 'Reviewer';
	insert cr;

	// Asset 1
	Opportunity_Line_Item__c oppLine = new Opportunity_Line_Item__c();
	oppLine.Line_Item_Type__c = 'Asset';
	oppline.Name = 'Test 1';
	oppLine.Opportunity__c = opp1.Id;
	oppLine.Planned_Install_City__c = 'Test';
	oppLine.Planned_Install_State__c = 'Test';
	oppLine.Planned_Install_Street__c = 'Test';
	oppLine.Planned_ZIP_Code__c = 'Test';
	insert oppLine;

	// Asset 2
	oppLine = new Opportunity_Line_Item__c();
	oppLine.Line_Item_Type__c = 'Asset';
	oppline.Name = 'Test 2';
	oppLine.Opportunity__c = opp1.Id;
	oppLine.Planned_Install_City__c = 'Test';
	oppLine.Planned_Install_State__c = 'Test';
	oppLine.Planned_Install_Street__c = 'Test';
	oppLine.Planned_ZIP_Code__c = 'Test';
	insert oppLine;

	// Asset 2
	oppLine = new Opportunity_Line_Item__c();
	oppLine.Line_Item_Type__c = 'Asset';
	oppline.Name = 'Test 3';
	oppLine.Opportunity__c = opp1.Id;
	oppLine.Planned_Install_City__c = 'Test';
	oppLine.Planned_Install_State__c = 'Test';
	oppLine.Planned_Install_Street__c = 'Test';
	oppLine.Planned_ZIP_Code__c = 'Test';
	insert oppLine;

	// Fees
	oppLine = new Opportunity_Line_Item__c();
	oppLine.Line_Item_Type__c = 'Fee';
	oppline.Name = 'Test';
	oppLine.Opportunity__c = opp1.Id;
	oppLine.Amount__c = 20;
	insert oppLine;

	// Fees
	oppLine = new Opportunity_Line_Item__c();
	oppLine.Line_Item_Type__c = 'Fee';
	oppline.Name = 'Test';
	oppLine.Opportunity__c = opp1.Id;
	oppLine.Amount__c = 20;
	insert oppLine;

	Quote q = new Quote();
	q.Name = 'Quote5';
	q.OpportunityId = opp1.id;
	q.Is_Primary__c = true;
	insert q;

	Quote_Line__c qLine = new Quote_Line__c();
	qLine.Quote__c = q.Id;
	qLine.Equipment_Type__c = 'Asset';
	insert qLine;

	qLine = new Quote_Line__c();
	qLine.Quote__c = q.Id;
	qLine.Equipment_Type__c = 'Add-on';
	insert qLine;

	Contract__c cont = new Contract__c();
	cont.UNQ_Opportunity__c='12345';
	cont.UNQ_Customer__c='123';
	cont.UNQ_Vendor__c='1234';
	cont.UNQ_Contract__c='1234CONTRACT';
	cont.UNQ_Program__c='Trac_Program';
	cont.Status_Text__c = 'BOOKED';
	cont.Name='test contract';
	cont.Account__c = at.id;
	cont.End_User__c = at.id;
	insert cont;

	//Insert asset
	Asset__c ast = new Asset__c();
	ast.Contract__c = cont.id;
	ast.Name = '12345';
	ast.Asset_City_Install_Address__c = 'Test';
	ast.Asset_Install_Address_Line_1__c = 'Test';
	ast.Asset_Install_Address_Line_2__c = 'Test';
	ast.Asset_Postal_Code_Install_Address__c = 'Test';
	ast.Asset_State_Install_Address__c = 'Test';
	insert ast;
}

@isTest static void testEnroll() {

	Opportunity existingOpp = [SELECT Id FROM Opportunity LIMIT 1];
	List<Opportunity_Line_Item__c> asset = [
		SELECT Id, Amount__c
		FROM Opportunity_Line_Item__c
		WHERE Opportunity__c = : existingOpp.Id
		                       AND Line_Item_Type__c = 'Asset'
	];
	List<Opportunity_Line_Item__c> serviceFees = [
		SELECT Id, Amount__c
		FROM Opportunity_Line_Item__c
		WHERE Opportunity__c = : existingOpp.Id
		                       AND Line_Item_Type__c = 'Fee'
	];

	// Asset Records
	List<Map<String, String> > assetRecords = new List<Map<String, String> >();

	// New fee
	Map<String, String> record = new Map<String, String>();
	record.put('name', 'Test');
	record.put('id', asset[0].Id);
	record.put('opportunity', existingOpp.Id);
	record.put('assetLocation', 'Test, Test, Test, Test');
	record.put('deliveryDate', '2022-07-26');
	record.put('serviceFee', '100');
	//record.put('serviceFeeId', '');
	record.put('taxExempt', 'true');
	record.put('serialNumber', 'Test');
	assetRecords.add(record);

	// Existing fee with amount
	record = new Map<String, String>();
	record.put('name', 'Test');
	record.put('id', asset[1].Id);
	record.put('opportunity', existingOpp.Id);
	record.put('assetLocation', 'Test, Test, Test, Test');
	record.put('deliveryDate', '2022-07-26');
	record.put('serviceFee', '100');
	record.put('serviceFeeId', serviceFees[0].Id);
	record.put('taxExempt', 'true');
	record.put('serialNumber', 'Test');
	assetRecords.add(record);

	// Existing fee without amount
	record = new Map<String, String>();
	record.put('name', 'Test');
	record.put('id', asset[2].Id);
	record.put('opportunity', existingOpp.Id);
	record.put('assetLocation', 'Test, Test, Test, Test');
	record.put('deliveryDate', '2022-07-26');
	record.put('serviceFee', '');
	record.put('serviceFeeId', serviceFees[1].Id);
	record.put('taxExempt', 'true');
	record.put('serialNumber', 'Test');
	assetRecords.add(record);

	// Signer Details
	List<Map<String, String> > signersRecords = new List<Map<String, String> >();
	List<OpportunityContactRole> ocrs = [
		SELECT Id, Role, ContactId
		FROM OpportunityContactRole
		WHERE OpportunityId = : existingOpp.Id
	];

	// Signer with UBOID
	Map<String, String> ocr = new Map<String, String>();
	ocr.put('Id', ocrs[0].Id);
	ocr.put('uboID', ocrs[0].Id);
	ocr.put('firstName', 'Test');
	ocr.put('middleName', 'Test');
	ocr.put('lastName', 'Test');
	ocr.put('titleValue', 'Test');
	ocr.put('emailValue', 'test@dllgroup.com');
	signersRecords.add(ocr);

	// Signer without UBOID
	ocr = new Map<String, String>();
	ocr.put('Id', ocrs[0].Id);
	ocr.put('firstName', 'Test');
	ocr.put('middleName', 'Test');
	ocr.put('lastName', 'Test');
	ocr.put('titleValue', 'Test');
	ocr.put('emailValue', 'test@dllgroup.com');
	signersRecords.add(ocr);

	// Signer with ContactId
	ocr = new Map<String, String>();
	ocr.put('Id', ocrs[0].ContactId);
	ocr.put('firstName', 'Test');
	ocr.put('middleName', 'Test');
	ocr.put('lastName', 'Test');
	ocr.put('titleValue', 'Test');
	ocr.put('emailValue', 'test@dllgroup.com');
	signersRecords.add(ocr);

	// Billing Address
	List<Map<String, String> > billingAddresses = new List<Map<String, String> >();
	Map<String, String> billingAddress = new Map<String, String>();
	billingAddress.put('addressLineOne', 'Test');
	billingAddress.put('addressLineTwo', 'Test');
	billingAddress.put('city', 'Test');
	billingAddress.put('state', 'Test');
	billingAddress.put('country', 'Test');
	billingAddress.put('ZIPCode', 'Test');
	billingAddresses.add(billingAddress);

	Test.startTest();
	Opportunity opp = EnrollController.getOpportunityData(existingOpp.Id);
	EnrollController.startOppEnroll(existingOpp.Id, 'Document Request Draft');
	List<Quote_Line__c> quoteLines = EnrollController.getQuoteLineAccessoryData(existingOpp.Id);
	List<Quote_Line__c> quoteLinesData = EnrollController.getQuoteLineData(existingOpp.Id);
	String customerId = EnrollController.getCustomerId('123', true);
	List<String> values = EnrollController.picklistValues('Opportunity', 'Sub_stage__c');
	EnrollController.updateStep('Review Specs', existingOpp.Id);
	List<Quote_Line__c> allQuoteLinesData = EnrollController.getAllQuoteLineData(existingOpp.Id);
	Opportunity endUser = EnrollController.getEndUserData(existingOpp.Id);
	EnrollController.getContactField(existingOpp.Id);
	Map<String, String> createPicklistValues = EnrollController.createPicklistValues('Opportunity', 'Sub_stage__c', existingOpp.Id);
	List<Opportunity_Line_Item__c> getAssetDetails = EnrollController.getAssetDetails(existingOpp.Id);
	EnrollController.getReviewerField(existingOpp.Id);
	EnrollController.updateAssetDetails(assetRecords);
	EnrollController.updateSignersDetails(signersRecords, existingOpp.Id);
	EnrollController.updateReviewersDetails(signersRecords, existingOpp.Id);
	EnrollController.getBillingContactData(existingOpp.Id);
	EnrollController.updateContactRoleData(signersRecords, existingOpp.Id);
	EnrollController.saveDocusignToOpp(existingOpp.Id, 'true');
	EnrollController.saveDocusignToOpp(existingOpp.Id, 'false');
	//EnrollController.getRelatedFilesByRecordId(existingOpp.Id);
	EnrollController.getDocusignValueFromOpp(existingOpp.Id);
	EnrollController.saveNewBillingAddress(existingOpp.Id, billingAddresses);
	EnrollControllerWithoutSharing.saveNewBillingAddress(existingOpp.Id, billingAddresses);
	Test.stopTest();
}
}