force-app/main/default/objects/Opportunity/fields/Application_Date__c.field-meta.xml
<CustomField>
    <fullName>Application_Date__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>This is the date the application is first entered in the source system.</inlineHelpText>
    <label>Application Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Commercial_Finance__c.field-meta.xml
<CustomField>
    <fullName>Commercial_Finance__c</fullName>
    <label>Commercial Finance</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>No</fullName>
            </value>
            <value>
                <fullName>Yes: Indirect - Tier 1</fullName>
            </value>
            <value>
                <fullName>Yes: Direct - Tier 1</fullName>
            </value>
            <value>
                <fullName>Yes: Direct - Tier 2</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/End_User__c.field-meta.xml
<CustomField>
    <fullName>End_User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Use this field to look up an existing Customer</inlineHelpText>
    <label>End User Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Opportunities (End User)</relationshipLabel>
    <relationshipName>Opportunities_End_User</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Existing_Match__c.field-meta.xml
<CustomField>
    <fullName>Existing_Match__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Existing Match</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Sales_Rep_ID__c.field-meta.xml
<CustomField>
    <fullName>Sales_Rep_ID__c</fullName>
    <description>External ID for Sales Rep</description>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <label>Sales Rep ID</label>
    <length>125</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/UNQ_Opportunity__c.field-meta.xml
<CustomField>
    <fullName>UNQ_Opportunity__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <label>UNQ Opportunity</label>
    <length>125</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/OpportunityMatchBatchSchedulerTest.cls
@isTest
public class OpportunityMatchBatchSchedulerTest {
    

    @isTest
    public static void OpportunityMatchUpdatesTest(){
        Account acc =new Account();
        acc.Name='test';
        acc.Technology_Solutions__c=false;
        acc.CleanTech__c=false;
        acc.Commercial_Finance__c=false;
        acc.BillingStreet = '3321 LEGION RD';
        acc.BillingCity = 'HOPE MILLS5';
        acc.BillingPostalCode = '28348-1652';
        acc.BillingState = 'North Carolina2';
        acc.BillingCountry = 'US';
        insert acc;
 

        Opportunity opp = new Opportunity();
        opp.Name = 'test';
        opp.End_User__c = acc.Id;
        opp.StageName = 'On Hold';
        opp.Type ='New';
        opp.Sales_Rep_ID__c = '1234';
        opp.Amount = 20000;
        opp.UNQ_Opportunity__c = 'APPNUM';
        opp.Application_Date__c = Date.today();
        insert opp;

        Opportunity match = new Opportunity();
        match.Name = opp.Name;
        match.End_User__c = acc.Id;
        match.StageName = 'On Hold';
        opp.Type ='New';
        match.Existing_Match__c = opp.Id;
        match.Sales_Rep_ID__c = 'DIFF';
        match.Amount = 1;
        match.UNQ_Opportunity__c = 'DIFFAPPNUM';
        match.Application_Date__c = Date.today().addMonths(1);
        insert match;

        Set<Id> oppIds = new Set<Id>();
        oppIds.add(opp.Id);
        oppIds.add(match.Id);

        OpportunityMatchBatchScheduler scheduler = new OpportunityMatchBatchScheduler();

        Test.startTest();
        scheduler.execute(null);
        Test.stopTest();

        List<Opportunity> updatedOpps = [SELECT Id, Sales_Rep_ID__c FROM Opportunity WHERE Id IN: oppIds];

        System.assertEquals(1, updatedOpps.size());
        System.assertEquals(match.Sales_Rep_ID__c, updatedOpps[0].Sales_Rep_ID__c);
    }

}