force-app/main/default/objects/Opportunity/fields/Application_Date__c.field-meta.xml
<CustomField>
    <fullName>Application_Date__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>This is the date the application is first entered in the source system.</inlineHelpText>
    <label>Application Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Application_Number__c.field-meta.xml
<CustomField>
    <fullName>Application_Number__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <label>Application Number</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/End_User__c.field-meta.xml
<CustomField>
    <fullName>End_User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Use this field to look up an existing Customer</inlineHelpText>
    <label>End User Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Opportunities (End User)</relationshipLabel>
    <relationshipName>Opportunities_End_User</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Nickname__c.field-meta.xml
<CustomField>
    <fullName>Nickname__c</fullName>
    <description>Nickname given to shell opportunity record when Quote is created from DLL on Demand Portal.
This field is used since existing opportunity name works with workflow.</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Nickname given to opportunity</inlineHelpText>
    <label>Nickname</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Opportunity_Name__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Name__c</fullName>
    <businessOwnerUser>mmikael.franzen@dllgroup.com.st01d06</businessOwnerUser>
    <description>Name of the Opportunity</description>
    <formula>IF( $Profile.Name = &apos;Nordics Community Profile&apos;,
   HYPERLINK(&quot;/partners/s/quote?oppId=&quot;&amp; Id, Name,&quot;_self&quot;), 
   HYPERLINK(&quot;/lightning/r/Opportunity/&quot; + Id + &quot;/view&quot;, Name, &quot;_self&quot;)
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Name of the Opportunity</inlineHelpText>
    <label>Opportunity Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Partner_Sales_Rep__c.field-meta.xml
<CustomField>
    <fullName>Partner_Sales_Rep__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup to Contact for Partner Sales Rep Name</description>
    <label>Partner Sales Rep</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Opportunities (Partner Sales Rep)</relationshipLabel>
    <relationshipName>Opportunities1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Sub_Stage__c.field-meta.xml
<CustomField>
    <fullName>Sub_Stage__c</fullName>
    <description>Opportunity sub stages to be used by each BU</description>
    <label>Sub-Stage</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>StageName</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Warm Leads Identified</fullName>
            </value>
            <value>
                <fullName>On Hold</fullName>
            </value>
            <value>
                <fullName>Prospect</fullName>
            </value>
            <value>
                <fullName>Customer Meeting</fullName>
            </value>
            <value>
                <fullName>Executive Endorsement</fullName>
            </value>
            <value>
                <fullName>Nondisclosure Agreement Executed</fullName>
            </value>
            <value>
                <fullName>Required Functional Approvals Complete (Table 1)</fullName>
            </value>
            <value>
                <fullName>Workshop Hosted</fullName>
            </value>
            <value>
                <fullName>Principles Document/Term Sheet Drafted</fullName>
            </value>
            <value>
                <fullName>Required Functional Approvals Complete (Table 2)</fullName>
            </value>
            <value>
                <fullName>Principles Document/Term Sheet Signed</fullName>
            </value>
            <value>
                <fullName>Program Fact Sheet</fullName>
            </value>
            <value>
                <fullName>Development of Offer</fullName>
            </value>
            <value>
                <fullName>Vendor Risk Application</fullName>
            </value>
            <value>
                <fullName>Determine Risk Acceptance Criteria</fullName>
            </value>
            <value>
                <fullName>ABC Assessment</fullName>
            </value>
            <value>
                <fullName>Remarketing Arrangement</fullName>
            </value>
            <value>
                <fullName>Profit &amp; Loss Calculation</fullName>
            </value>
            <value>
                <fullName>Program Agreement Under Review</fullName>
            </value>
            <value>
                <fullName>DLL Selected</fullName>
            </value>
            <value>
                <fullName>Required Functional Approvals Complete (Table 3)</fullName>
            </value>
            <value>
                <fullName>Local Due Diligence &amp; Approval Committee</fullName>
            </value>
            <value>
                <fullName>Global Credit Committee Approval</fullName>
            </value>
            <value>
                <fullName>Determine Vendor Reporting Requirements</fullName>
            </value>
            <value>
                <fullName>Create Rollout Plan (Global)</fullName>
            </value>
            <value>
                <fullName>Implementation Plan (Local)</fullName>
            </value>
            <value>
                <fullName>Agreement Executed</fullName>
            </value>
            <value>
                <fullName>Assigned Local Implementation</fullName>
            </value>
            <value>
                <fullName>MVP Implemented</fullName>
            </value>
            <value>
                <fullName>Quote Draft</fullName>
            </value>
            <value>
                <fullName>Application Draft</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/recordTypes/Retail.recordType-meta.xml
<RecordType>
    <fullName>Retail</fullName>
    <active>true</active>
    <businessProcess>Transactional</businessProcess>
    <description>Vendor/Dealer led Opportunity</description>
    <label>Retail</label>
</RecordType>

force-app/main/default/classes/AccountPageHeader.cls
/**
 * @description       : Apex class for Account Page Header.
 * @author            : Kritika Sharma (Traction on Demand)
 * @group             : 
 * @last modified on  : 10-03-2022
 * @last modified by  : Kritika Sharma
**/
public with sharing class AccountPageHeader {
    @AuraEnabled(cacheable=true)
    public static Account getAccountData(Id accountId){
        return [
                SELECT Id, Name, AccountNumber, Industry
                FROM Account
                WHERE Id = :accountId
                LIMIT 1
        ];
    }

    @AuraEnabled(cacheable=false)
    public static String createNewOppForCreditCheck(String endUserId) {
        Opportunity newOpp = new Opportunity();
        newOpp.RecordTypeId = [select Id from RecordType where DeveloperName = 'Retail' AND sObjectType = 'Opportunity' limit 1].Id;
        newOpp.Nickname__c = 'Credit Check';
        if (!String.isBlank(endUserId)) {
            newOpp.End_User__c = endUserId;
        }
        newOpp.CloseDate = System.today() + 30;
        newOpp.StageName = 'Quoting';
        newOpp.Sub_Stage__c = 'Application Draft';
        newOpp.ForecastCategoryName = 'Omitted';
        newOpp.Amount = 0;
        newOpp.CurrencyIsoCode = 'USD';
        newOpp.Type = 'Credit Check';

        try {
            insert newOpp;
        } catch (DmlException e) {
            throw new AuraHandledException(e.getMessage());
        }

        return newOpp.Id;
    }
    
    @AuraEnabled
    public static Integer getTotalRecords(String accountId ) {
        String querySQL;
		Integer totalNumberOfRows;
		querySQL = 'SELECT COUNT() FROM Opportunity WHERE End_User__c = :accountId AND RecordType.DeveloperName = \'Retail\'';
		totalNumberOfRows = Database.countQuery(querySQL);
		return totalNumberOfRows;
    }
    
	@AuraEnabled(cacheable=true)
	public static List<Opportunity> getRecords(String accountId, Integer rowLimit, Integer rowOffset){
                  
        string querySQL;   
        list<Opportunity> oppList = new List<Opportunity>();
        
        system.debug(accountId);
                         
        querySQL = 'SELECT Opportunity_Name__c, Name, Amount, Application_Date__c, Application_Number__c, End_User__c, Partner_Sales_Rep__r.Name, Sub_Stage__c, Account.Name ' +
                   ' FROM Opportunity WHERE End_User__c = \'' + accountId + '\' ORDER BY CreatedDate desc LIMIT ' + rowLimit + ' OFFSET ' + rowOffset;
		system.debug(querySQL);
        oppList = Database.query(querySQL);
        system.debug(oppList);
        return oppList;
	}    
    
}