force-app/main/default/objects/Opportunity/fields/Application_Date__c.field-meta.xml
<CustomField>
    <fullName>Application_Date__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>This is the date the application is first entered in the source system.</inlineHelpText>
    <label>Application Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Application_Number__c.field-meta.xml
<CustomField>
    <fullName>Application_Number__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <label>Application Number</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Approval_Letter_Expiration_Date__c.field-meta.xml
<CustomField>
    <fullName>Approval_Letter_Expiration_Date__c</fullName>
    <description>This field contains the Approval Letter Expiration Date from Wayne/Mosaic</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Approval Letter Expiration Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/End_User__c.field-meta.xml
<CustomField>
    <fullName>End_User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Use this field to look up an existing Customer</inlineHelpText>
    <label>End User Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Opportunities (End User)</relationshipLabel>
    <relationshipName>Opportunities_End_User</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/End_User_Company_Name__c.field-meta.xml
<CustomField>
    <fullName>End_User_Company_Name__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Use this field when the customer does not exist in Salesforce</inlineHelpText>
    <label>End User Name (Text)</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Nickname__c.field-meta.xml
<CustomField>
    <fullName>Nickname__c</fullName>
    <description>Nickname given to shell opportunity record when Quote is created from DLL on Demand Portal.
This field is used since existing opportunity name works with workflow.</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Nickname given to opportunity</inlineHelpText>
    <label>Nickname</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Opportunity_Number__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Number__c</fullName>
    <businessOwnerGroup>North_America_Admins</businessOwnerGroup>
    <description>This is quote number that is used to reference a group of DLL on Demand quote options. It appears in the Price Quote field in MOSAIC.</description>
    <displayFormat>{YY}{MM}-{0000}</displayFormat>
    <inlineHelpText>This DLL on Demand number represents a set of related quote options, not necessarily a specific record. It is also passed to MOSAIC as the Price Quote value.</inlineHelpText>
    <label>Quote No.</label>
    <type>AutoNumber</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Partner_Sales_Rep__c.field-meta.xml
<CustomField>
    <fullName>Partner_Sales_Rep__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup to Contact for Partner Sales Rep Name</description>
    <label>Partner Sales Rep</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Opportunities (Partner Sales Rep)</relationshipLabel>
    <relationshipName>Opportunities1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Sub_Stage__c.field-meta.xml
<CustomField>
    <fullName>Sub_Stage__c</fullName>
    <description>Opportunity sub stages to be used by each BU</description>
    <label>Sub-Stage</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>StageName</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Warm Leads Identified</fullName>
            </value>
            <value>
                <fullName>On Hold</fullName>
            </value>
            <value>
                <fullName>Prospect</fullName>
            </value>
            <value>
                <fullName>Customer Meeting</fullName>
            </value>
            <value>
                <fullName>Executive Endorsement</fullName>
            </value>
            <value>
                <fullName>Nondisclosure Agreement Executed</fullName>
            </value>
            <value>
                <fullName>Required Functional Approvals Complete (Table 1)</fullName>
            </value>
            <value>
                <fullName>Workshop Hosted</fullName>
            </value>
            <value>
                <fullName>Principles Document/Term Sheet Drafted</fullName>
            </value>
            <value>
                <fullName>Required Functional Approvals Complete (Table 2)</fullName>
            </value>
            <value>
                <fullName>Principles Document/Term Sheet Signed</fullName>
            </value>
            <value>
                <fullName>Program Fact Sheet</fullName>
            </value>
            <value>
                <fullName>Development of Offer</fullName>
            </value>
            <value>
                <fullName>Vendor Risk Application</fullName>
            </value>
            <value>
                <fullName>Determine Risk Acceptance Criteria</fullName>
            </value>
            <value>
                <fullName>ABC Assessment</fullName>
            </value>
            <value>
                <fullName>Remarketing Arrangement</fullName>
            </value>
            <value>
                <fullName>Profit &amp; Loss Calculation</fullName>
            </value>
            <value>
                <fullName>Program Agreement Under Review</fullName>
            </value>
            <value>
                <fullName>DLL Selected</fullName>
            </value>
            <value>
                <fullName>Required Functional Approvals Complete (Table 3)</fullName>
            </value>
            <value>
                <fullName>Local Due Diligence &amp; Approval Committee</fullName>
            </value>
            <value>
                <fullName>Global Credit Committee Approval</fullName>
            </value>
            <value>
                <fullName>Determine Vendor Reporting Requirements</fullName>
            </value>
            <value>
                <fullName>Create Rollout Plan (Global)</fullName>
            </value>
            <value>
                <fullName>Implementation Plan (Local)</fullName>
            </value>
            <value>
                <fullName>Agreement Executed</fullName>
            </value>
            <value>
                <fullName>Assigned Local Implementation</fullName>
            </value>
            <value>
                <fullName>MVP Implemented</fullName>
            </value>
            <value>
                <fullName>Quote Draft</fullName>
            </value>
            <value>
                <fullName>Booked</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Calculation</fullName>
            </value>
            <value>
                <fullName>Competitor</fullName>
            </value>
            <value>
                <fullName>Cash</fullName>
            </value>
            <value>
                <fullName>Customer Not Ready</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/recordTypes/Retail.recordType-meta.xml
<RecordType>
    <fullName>Retail</fullName>
    <active>true</active>
    <businessProcess>Transactional</businessProcess>
    <description>Vendor/Dealer led Opportunity</description>
    <label>Retail</label>
</RecordType>

force-app/main/default/classes/OpportunityListView.cls
/*
 * OpportunityListView
 * The controller for the OpportunityListView LWC
 *
 * change log:
 * 2022-07-01: HV patched the Application Number sorting column issue.
 */

public with sharing class OpportunityListView {

    @AuraEnabled(cacheable=true)
    public static List<Opportunity> getOpportunities(
        Integer rowLimit,
        Integer rowOffset,
        String submittedDate,
        String partnerStatus,
        String searchAllValue,
        String sortBy,
        String sortDirection
        ){
            string querySQL;   
            string condition;
            string nullSeq;
            string sortByConvert;
            
            List<string> substagesEX = new List<string>{'Booked', 'Calculation', 'Cash', 'Competitor', 'Customer Not Ready', 'Quote Draft', 'Quoting & Proposal'};

            if(String.isNotBlank(sortDirection)){
                if(sortDirection == 'asc'){
                    nullSeq = 'first';
                }
                else{
                    nullSeq = 'last';
                }
            }

            // Handle field mapping for columns where the variable doesn't match the field name.
            if(sortBy == 'EndUserURL') {
                sortByConvert = 'End_User_Company_Name__c';
            }else if(sortBy == 'quoteNumberURL') {
                sortByConvert = 'Opportunity_Number__c';            
            }else if(sortBy == 'ApplicationNumberUrl'){

                // Double column sorting supports defaulting the application number to the nickname when it's empty.
                sortByConvert = 'Application_Number__c, Nickname__c';
            } else {
                sortByConvert = sortBy;
            } 
                      
            list<Opportunity> oppList = new List<Opportunity>(); 
                     
            condition= getCondition(rowLimit,rowOffset,submittedDate,partnerStatus,searchAllValue);  
            if(String.isNotBlank(condition)){
                if(String.isNotBlank(sortBy)){
                    querySQL ='SELECT Id,Application_Number__c,Nickname__c,Amount,End_User__c,End_User_Company_Name__c,Sub_Stage__c,Application_Date__c,Approval_Letter_Expiration_Date__c,Partner_Sales_Rep__r.Name, Opportunity_Number__c '+
                ' FROM Opportunity WHERE Sub_Stage__c not in :substagesEX and ' + condition + ' ORDER BY ' + sortByConvert  + ' ' + sortDirection + ' NULLS ' + nullSeq +
                ' LIMIT ' + rowLimit + ' OFFSET ' + rowOffset;
                }
                else {
                    querySQL ='SELECT Id,Application_Number__c,Nickname__c,Amount,End_User__c,End_User_Company_Name__c,Sub_Stage__c,Application_Date__c,Approval_Letter_Expiration_Date__c,Partner_Sales_Rep__r.Name, Opportunity_Number__c '+
                ' FROM Opportunity WHERE Sub_Stage__c not in :substagesEX and ' + condition + ' LIMIT ' + rowLimit + ' OFFSET ' + rowOffset;
                }
            } 
            else{
                if(String.isNotBlank(sortBy)){
                    querySQL = 'SELECT Id,Application_Number__c,Nickname__c,Amount,End_User__c,End_User_Company_Name__c,Sub_Stage__c,Application_Date__c,Approval_Letter_Expiration_Date__c,Partner_Sales_Rep__r.Name, Opportunity_Number__c '+
                ' FROM Opportunity WHERE Sub_Stage__c not in :substagesEX '+ ' ORDER BY ' + sortByConvert + ' ' + sortDirection + ' NULLS ' + nullSeq +
                ' LIMIT ' + rowLimit + ' OFFSET ' + rowOffset;
                }
                else {
                    querySQL = 'SELECT Id,Application_Number__c,Nickname__c,Amount,End_User__c,End_User_Company_Name__c,Sub_Stage__c,Application_Date__c,Approval_Letter_Expiration_Date__c,Partner_Sales_Rep__r.Name, Opportunity_Number__c '+
                ' FROM Opportunity WHERE Sub_Stage__c not in :substagesEX ' + ' LIMIT ' + rowLimit + ' OFFSET ' + rowOffset;
                }
            }

        oppList = Database.query(querySQL);

        // Default the Application # to the nickname if it's blank.
        if(oppList.size() > 0){
            for(Opportunity opp : oppList){
                if(opp.Application_Number__c == null || opp.Application_Number__c == ''){
                    opp.Application_Number__c = opp.Nickname__c;
                }
            }
        }

        return oppList;
    }

    @AuraEnabled(cacheable=true)
    public static Integer getOpportunitiesNum(
        Integer rowLimit,
        Integer rowOffset,
        String submittedDate,
        String partnerStatus,
        String searchAllValue
        ){
            String querySQL;
            string condition;
            Integer totalNumberOfRows;

            condition= getCondition(rowLimit,rowOffset,submittedDate,partnerStatus,searchAllValue);  
            if(String.isNotBlank(condition)){
                querySQL = 'SELECT COUNT() FROM Opportunity WHERE ' + condition;
            }
            else{
                querySQL = 'SELECT COUNT() FROM Opportunity';
            }
            totalNumberOfRows = Database.countQuery(querySQL);
            return totalNumberOfRows;
        }


    public static string getCondition(
        Integer rowLimit,
        Integer rowOffset,
        String submittedDate,
        String partnerStatus,
        String searchAllValue
    ){
        String condition = '';
        String startDate;
        String startDateFormat;
        String endDate;
        String endDateFormat;

        System.debug('submittedDate ' + submittedDate);

        if(String.isNotBlank(submittedDate)){
            if(submittedDate=='30D'){
                condition = 'Application_Date__c = ' + ' LAST_N_DAYS:30 ';
            }
            else{
                if(submittedDate=='60D'){
                    condition = 'Application_Date__c = ' + ' LAST_N_DAYS:60 ';
                }
                else{
                    if(submittedDate=='6M'){
                        condition = 'Application_Date__c = ' + ' LAST_N_MONTHS:6 ';
                    }
                    else{
                        if(submittedDate=='12M'){
                            condition = 'Application_Date__c = ' + ' LAST_N_MONTHS:12 ';
                        }
                        else{
                            startDate = submittedDate + '-01-01';
                            endDate = submittedDate + '-12-31';                         
                            condition = 'Application_Date__c >= ' + startDate + ' AND Application_Date__c <= ' + endDate;
                        }
                    }
                }
            }
        }  

        if(String.isNotBlank(partnerStatus)){
            system.debug('FNS condition::'+ condition);
            if(partnerStatus=='Cancelled'){
                if(String.isNotBlank(condition)){
                    condition += ' AND ' + '(Sub_Stage__c =  \'' + 'Cancelled' + '\'' + ' OR ' + 'Sub_Stage__c =  \'' + 'Cash' + '\'' + ' OR ' + 'Sub_Stage__c =  \'' + 'Competitor' + '\'' + ' OR ' + 'Sub_Stage__c =  \'' + 'Customer Not Ready' + '\')';
                }
                else{
                    condition += '(Sub_Stage__c =  \'' + 'Cancelled' + '\'' + ' OR ' + 'Sub_Stage__c =  \'' + 'Cash' + '\'' + ' OR ' + 'Sub_Stage__c =  \'' + 'Competitor' + '\'' + ' OR ' + 'Sub_Stage__c =  \'' + 'Customer Not Ready' + '\')';
                }
            }
            else{
                if(String.isNotBlank(condition)){
                    condition += ' AND ' + 'Sub_Stage__c =  \'' + partnerStatus + '\'';
                    system.debug('FNS condition::'+ condition);
                }
                else{
                    condition += 'Sub_Stage__c =  \'' + partnerStatus + '\'';
                    system.debug('FNS condition::'+ condition);
                }
            }
        }

        condition += (String.isNotBlank(searchAllValue)
            ? (String.isNotBlank(condition) ? +' AND ' : '') +
              ' (Application_Number__c LIKE \'' +
              '%' +
              searchAllValue +
              '%\'' + ' OR ' +
              ' End_User_Company_Name__c LIKE \'' +
              '%' +
              searchAllValue +
              '%\')'
            : '');
        System.debug('condition ' + condition);
        
        //Start: PBI - 829854 - Author: Fernando Nereu de Souza
        if(String.isNotBlank(condition)){
            condition += ' AND RecordType.DeveloperName = \'Retail\'';
        }
        else{
            condition += 'RecordType.DeveloperName = \'Retail\'';
        }
        //End: PBI - 829854 - Author: Fernando Nereu de Souza
        return condition;
    }
}