force-app/main/default/objects/Opportunity/fields/Application_Date__c.field-meta.xml
<CustomField>
    <fullName>Application_Date__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>This is the date the application is first entered in the source system.</inlineHelpText>
    <label>Application Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Application_Number__c.field-meta.xml
<CustomField>
    <fullName>Application_Number__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <label>Application Number</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Billing_Address_Preference__c.field-meta.xml
<CustomField>
    <fullName>Billing_Address_Preference__c</fullName>
    <description>For DLL on Demand Portal - records whether the user selected the default Billing Address for the End User Account (System Address) or entered a new Billing Address</description>
    <label>Billing Address Preference</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Use existing billing address</fullName>
            </value>
            <value>
                <fullName>Enter new billing address</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Business_Unit1__c.field-meta.xml
<CustomField>
    <fullName>Business_Unit1__c</fullName>
    <defaultValue>$User.Business_Unit_TEXT__c</defaultValue>
    <label>Opportunity Business Unit</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Advanced Solutions</fullName>
            </value>
            <value>
                <fullName>Clean Technology</fullName>
            </value>
            <value>
                <fullName>Commercial Finance</fullName>
            </value>
            <value>
                <fullName>Construction, Transportation &amp; Infrastructure (CTI)</fullName>
            </value>
            <value>
                <fullName>Food &amp; Agriculture (F&amp;A)</fullName>
            </value>
            <value>
                <fullName>Golf and Turf (G&amp;T)</fullName>
            </value>
            <value>
                <fullName>Healthcare</fullName>
            </value>
            <value>
                <fullName>Office Equipment (OE)</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Pay Per Use</fullName>
            </value>
            <value>
                <fullName>Public Finance</fullName>
            </value>
            <value>
                <fullName>Technology Solutions</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Vendor Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/End_User__c.field-meta.xml
<CustomField>
    <fullName>End_User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Use this field to look up an existing Customer</inlineHelpText>
    <label>End User Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Opportunities (End User)</relationshipLabel>
    <relationshipName>Opportunities_End_User</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/End_User_Company_Name__c.field-meta.xml
<CustomField>
    <fullName>End_User_Company_Name__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Use this field when the customer does not exist in Salesforce</inlineHelpText>
    <label>End User Name (Text)</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Partner_Sales_Rep__c.field-meta.xml
<CustomField>
    <fullName>Partner_Sales_Rep__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup to Contact for Partner Sales Rep Name</description>
    <label>Partner Sales Rep</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Opportunities (Partner Sales Rep)</relationshipLabel>
    <relationshipName>Opportunities1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Sub_Stage__c.field-meta.xml
<CustomField>
    <fullName>Sub_Stage__c</fullName>
    <description>Opportunity sub stages to be used by each BU</description>
    <label>Sub-Stage</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>StageName</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Warm Leads Identified</fullName>
            </value>
            <value>
                <fullName>On Hold</fullName>
            </value>
            <value>
                <fullName>Prospect</fullName>
            </value>
            <value>
                <fullName>Customer Meeting</fullName>
            </value>
            <value>
                <fullName>Executive Endorsement</fullName>
            </value>
            <value>
                <fullName>Nondisclosure Agreement Executed</fullName>
            </value>
            <value>
                <fullName>Required Functional Approvals Complete (Table 1)</fullName>
            </value>
            <value>
                <fullName>Workshop Hosted</fullName>
            </value>
            <value>
                <fullName>Principles Document/Term Sheet Drafted</fullName>
            </value>
            <value>
                <fullName>Required Functional Approvals Complete (Table 2)</fullName>
            </value>
            <value>
                <fullName>Principles Document/Term Sheet Signed</fullName>
            </value>
            <value>
                <fullName>Program Fact Sheet</fullName>
            </value>
            <value>
                <fullName>Development of Offer</fullName>
            </value>
            <value>
                <fullName>Vendor Risk Application</fullName>
            </value>
            <value>
                <fullName>Determine Risk Acceptance Criteria</fullName>
            </value>
            <value>
                <fullName>ABC Assessment</fullName>
            </value>
            <value>
                <fullName>Remarketing Arrangement</fullName>
            </value>
            <value>
                <fullName>Profit &amp; Loss Calculation</fullName>
            </value>
            <value>
                <fullName>Program Agreement Under Review</fullName>
            </value>
            <value>
                <fullName>DLL Selected</fullName>
            </value>
            <value>
                <fullName>Required Functional Approvals Complete (Table 3)</fullName>
            </value>
            <value>
                <fullName>Local Due Diligence &amp; Approval Committee</fullName>
            </value>
            <value>
                <fullName>Global Credit Committee Approval</fullName>
            </value>
            <value>
                <fullName>Determine Vendor Reporting Requirements</fullName>
            </value>
            <value>
                <fullName>Create Rollout Plan (Global)</fullName>
            </value>
            <value>
                <fullName>Implementation Plan (Local)</fullName>
            </value>
            <value>
                <fullName>Agreement Executed</fullName>
            </value>
            <value>
                <fullName>Assigned Local Implementation</fullName>
            </value>
            <value>
                <fullName>MVP Implemented</fullName>
            </value>
            <value>
                <fullName>Quote Draft</fullName>
            </value>
            <value>
                <fullName>Booked</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/UNQ_Customer__c.field-meta.xml
<CustomField>
    <fullName>UNQ_Customer__c</fullName>
    <description>UNQ Customer ID from external system</description>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <label>UNQ Customer</label>
    <length>125</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/UNQ_Opportunity__c.field-meta.xml
<CustomField>
    <fullName>UNQ_Opportunity__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <label>UNQ Opportunity</label>
    <length>125</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Opportunity/fields/UNQ_Vendor__c.field-meta.xml
<CustomField>
    <fullName>UNQ_Vendor__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>UNQ_Vendor</label>
    <length>125</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity_Line_Item__c/Opportunity_Line_Item__c.object-meta.xml
<CustomObject>
    <description>Application line items are used in the DLL on Demand partner portal to represent assets and fees tracked during the credit application process. The standard object was not used as products and price books aren&apos;t used in the DoD portal currently.</description>
    <label>Opportunity Line Item</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Line Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Opportunity Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Opportunity_Line_Item__c/fields/Line_Item_Type__c.field-meta.xml
<CustomField>
    <fullName>Line_Item_Type__c</fullName>
    <businessOwnerGroup>North_America_Admins</businessOwnerGroup>
    <description>The type of line item used to indicate what the item is for and how to use it in calculations.</description>
    <inlineHelpText>The type of line item used to indicate what the item is for and how to use it in calculations.</inlineHelpText>
    <label>Line Item Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Asset</fullName>
            </value>
            <value>
                <fullName>Add-on</fullName>
            </value>
            <value>
                <fullName>Fee</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity_Line_Item__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <businessOwnerGroup>North_America_Admins</businessOwnerGroup>
    <description>The parent opportunity that the line item is for.</description>
    <inlineHelpText>The parent opportunity that the line item is for.</inlineHelpText>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipName>Application_Line_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Opportunity_Line_Item__c/fields/Planned_Install_Date__c.field-meta.xml
<CustomField>
    <fullName>Planned_Install_Date__c</fullName>
    <businessOwnerGroup>North_America_Admins</businessOwnerGroup>
    <description>The date the asset is anticipated to be delivered to the customer&apos;s planned install address.</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>The date the asset is anticipated to be delivered to the customer&apos;s planned install address.</inlineHelpText>
    <label>Planned Install Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/EnrollRequestDocsIncomingTest.cls
/*****************************************************************************************************************
 * Dll on Demand
 * 07/14/2022 - Geetha created Test class for EnrollRequestDocsIncoming PBI 762603 and 762605
 *******************************************************************************************************************/
@isTest
public class EnrollRequestDocsIncomingTest {
public static testMethod void method0() {

	List<Opportunity> oppList = new List<Opportunity>();

	Account at =new Account();
	at.Name='Service';
	insert at;

	contact ct =new contact();
	ct.LastName='test';
	ct.AccountId=at.id;
	ct.Email='arry@gmil.com';
	insert ct;

	Opportunity opp1= new Opportunity();
	opp1.application_number__c='A1';
	opp1.Type='Overline';
	opp1.Name='Service';
	opp1.StageName='Closed Won';
	opp1.Accountid=at.id;
	opp1.Contact__c=ct.id;
	opp1.CloseDate=system.today()+1;
	opp1.Amount=11.0;
	opp1.End_User__c=at.id;
	opp1.End_User_Company_Name__c = 'DANIEL INC.';
	opp1.Business_Unit1__c='Digital Imaging';
	opp1.Sub_Stage__c='Booked';
	opp1.Application_Date__c=system.today().addMonths(-3);
	opp1.UNQ_Customer__c='A1';
	opp1.UNQ_Vendor__c='A1';
	opp1.UNQ_Opportunity__c='A1';
	opp1.Application_Number__c = '123459';
	oppList.add(opp1);

	insert opp1;
	Test.startTest();
	EnrollRequestDocsIncoming.sendDocsForFunding(opp1.id);
	Test.stopTest();
}

public static testMethod void method1() {

	List<Opportunity> oppList = new List<Opportunity>();

	Account at =new Account();
	at.Name='Service';
	insert at;

	contact ct =new contact();
	ct.LastName='test';
	ct.AccountId=at.id;
	ct.Email='arry@gmil.com';
	insert ct;

	Opportunity opp1= new Opportunity();
	opp1.application_number__c='A1';
	opp1.Type='Overline';
	opp1.Name='Service';
	opp1.StageName='Closed Won';
	opp1.Accountid=at.id;
	opp1.Contact__c=ct.id;
	opp1.CloseDate=system.today()+1;
	opp1.Amount=11.0;
	opp1.End_User__c=at.id;
	opp1.End_User_Company_Name__c = 'DANIEL INC.';
	opp1.Business_Unit1__c='Digital Imaging';
	opp1.Sub_Stage__c='Booked';
	opp1.Application_Date__c=system.today().addMonths(-3);
	opp1.UNQ_Customer__c='A1';
	opp1.UNQ_Vendor__c='A1';
	opp1.UNQ_Opportunity__c='A1';
	opp1.Application_Number__c = '123459';
	oppList.add(opp1);

	insert opp1;
	Test.startTest();
	EnrollRequestDocsIncoming.sendEmailforOpportunity(opp1.id);
	Test.stopTest();
}

public static testMethod void method2() {

	List<Opportunity> oppList = new List<Opportunity>();

	Account at =new Account();
	at.Name='Service';
	insert at;

	contact ct =new contact();
	ct.LastName='Niranjan';
	ct.AccountId=at.id;
	ct.Email='arry@gmil.com';
	insert ct;

	Opportunity opp2= new Opportunity();
	opp2.application_number__c='A1';
	opp2.Type='Overline';
	opp2.Name='Service';
	opp2.StageName='Closed Won';
	opp2.Accountid=at.id;
	opp2.Contact__c=ct.id;
	opp2.CloseDate=system.today()+1;
	opp2.Amount=11.0;
	opp2.End_User__c=at.id;
	opp2.End_User_Company_Name__c = 'DANIEL INC.';
	opp2.Business_Unit1__c='Digital Imaging';
	opp2.Sub_Stage__c='Booked';
	opp2.Application_Date__c=system.today().addMonths(-3);
	opp2.UNQ_Customer__c='A1';
	opp2.UNQ_Vendor__c='A1';
	opp2.UNQ_Opportunity__c='A1';
	insert opp2;


	Messaging.InboundEnvelope env = new Messaging.InboundEnvelope();
	Messaging.InboundEmail mail = new Messaging.InboundEmail();

	mail.Subject = 'Application Number :' +opp2.Application_Number__c;
	mail.fromname = 'Geetha';
	env.fromAddress = 'geetha.bharadwaj@dllgroup.com';
	mail.plainTextBody = 'Test';

	//below code is for Document attachments
	Messaging.InboundEmail.BinaryAttachment docattachments = new Messaging.InboundEmail.BinaryAttachment();
	docattachments.body = blob.valueOf('my attachment Document');
	docattachments.fileName = 'docfile.doc';
	docattachments.mimeTypeSubType = 'text/plain';
	mail.binaryAttachments = new Messaging.inboundEmail.BinaryAttachment[] { docattachments };

	//below code is for Text attachments
	Messaging.InboundEmail.textAttachment txtAttachment = new Messaging.InboundEmail.textAttachment();
	txtAttachment.body = 'My text attachemnt body';
	txtAttachment.fileName = 'textfile.txt';
	txtAttachment.mimeTypeSubType = 'text/plain';
	mail.textAttachments = new Messaging.inboundEmail.TextAttachment[] { txtAttachment };


	Test.startTest();
	EnrollRequestDocsIncoming enrollreq = new EnrollRequestDocsIncoming();
	enrollreq.handleInboundEmail(mail, env);
	Test.stopTest();

}
public static testMethod void method3() {

	List<Opportunity> oppList = new List<Opportunity>();

	Account at =new Account();
	at.Name='Service';
	insert at;

	contact ct =new contact();
	ct.LastName='Niranjan';
	ct.AccountId=at.id;
	ct.Email='arry@gmil.com';
	insert ct;

	Opportunity opp1= new Opportunity();
	opp1.application_number__c='A1';
	opp1.Type='Overline';
	opp1.Name='Service';
	opp1.StageName='Closed Won';
	opp1.Accountid=at.id;
	opp1.Contact__c=ct.id;
	opp1.CloseDate=system.today()+1;
	opp1.Amount=11.0;
	opp1.End_User__c=at.id;
	opp1.End_User_Company_Name__c = 'DANIEL INC.';
	opp1.Business_Unit1__c='Digital Imaging';
	opp1.Sub_Stage__c='Booked';
	opp1.Application_Date__c=system.today().addMonths(-3);
	opp1.UNQ_Customer__c='A1';
	opp1.UNQ_Vendor__c='A1';
	opp1.UNQ_Opportunity__c='A1';
	opp1.billing_address_preference__c = 'Enter new billing address';
	insert opp1;

	Opportunity_Line_Item__c oli =  new Opportunity_Line_Item__c();
	oli.Name = 'oli1';
	oli.opportunity__c = opp1.id;
	oli.line_item_type__c = 'Asset';

	insert oli;


	Contact c1 = new Contact();
	c1.phone = '1234567891';
	c1.LastName = 'Billing Contact LN';
	c1.FirstName = 'Billing Contact FN';
	c1.MiddleName = 'Billing Contact MN';
	c1.Title = 'Mr';
	c1.Email = 'test@gmail.com';
	c1.AccountId = at.id;
	insert c1;

	OpportunityContactRole ocr1 = new OpportunityContactRole();
	ocr1.ContactId = c1.id;
	ocr1.Role = 'Billing Contact';
	ocr1.OpportunityId = opp1.id;
	insert ocr1;

	Contact c2 = new Contact();
	c2.phone = '1234567891';
	c2.LastName = 'Signer LN';
	c2.FirstName = 'Signer FN';
	c2.MiddleName = 'Signer MN';
	c2.Title = 'Mr';
	c2.Email = 'test@gmail.com';
	c2.AccountId = at.id;
	insert c2;

	OpportunityContactRole ocr2 = new OpportunityContactRole();
	ocr2.ContactId = c2.id;
	ocr2.Role = 'Signer';
	ocr2.OpportunityId = opp1.id;
	insert ocr2;

	Contact c3 = new Contact();
	c3.phone = '1234567891';
	c3.LastName = 'Reviewer LN';
	c3.FirstName = 'Reviewer FN';
	c3.MiddleName = 'Reviewer MN';
	c3.Title = 'Mr';
	c3.Email = 'test@gmail.com';
	c3.AccountId = at.id;
	insert c3;

	OpportunityContactRole ocr3 = new OpportunityContactRole();
	ocr3.ContactId = c3.id;
	ocr3.Role = 'Reviewer';
	ocr3.OpportunityId = opp1.id;
	insert ocr3;


	Messaging.InboundEnvelope env = new Messaging.InboundEnvelope();
	Messaging.InboundEmail mail = new Messaging.InboundEmail();

	mail.Subject = 'Application Number :' +opp1.Application_Number__c;
	mail.fromname = 'Geetha';
	env.fromAddress = 'geetha.bharadwaj@dllgroup.com';
	mail.plainTextBody = 'Test';

	//below code is for Document attachments
	Messaging.InboundEmail.BinaryAttachment docattachments = new Messaging.InboundEmail.BinaryAttachment();
	docattachments.body = blob.valueOf('my attachment Document');
	docattachments.fileName = 'docfile.doc';
	docattachments.mimeTypeSubType = 'text/plain';
	mail.binaryAttachments = new Messaging.inboundEmail.BinaryAttachment[] { docattachments };

	//below code is for Text attachments
	Messaging.InboundEmail.textAttachment txtAttachment = new Messaging.InboundEmail.textAttachment();
	txtAttachment.body = 'My text attachemnt body';
	txtAttachment.fileName = 'textfile.txt';
	txtAttachment.mimeTypeSubType = 'text/plain';
	mail.textAttachments = new Messaging.inboundEmail.TextAttachment[] { txtAttachment };


	Test.startTest();
	EnrollRequestDocsIncoming enrollreq = new EnrollRequestDocsIncoming();
	//enrollreq.handleInboundEmail(mail, env);
	EnrollRequestDocsIncoming.sendEmailforOpportunity(opp1.id);
	Test.stopTest();

}


public static testMethod void method4() {

	List<Opportunity> oppList = new List<Opportunity>();

	Account at =new Account();
	at.Name='Service';
	insert at;

	contact ct =new contact();
	ct.LastName='Niranjan';
	ct.AccountId=at.id;
	ct.Email='arry@gmil.com';
	insert ct;

	Opportunity opp1= new Opportunity();
	opp1.application_number__c='A1';
	opp1.Type='Overline';
	opp1.Name='Service';
	opp1.StageName='Closed Won';
	opp1.Accountid=at.id;
	opp1.Contact__c=ct.id;
	opp1.CloseDate=system.today()+1;
	opp1.Amount=11.0;
	opp1.End_User__c=at.id;
	opp1.End_User_Company_Name__c = 'DANIEL INC.';
	opp1.Business_Unit1__c='Digital Imaging';
	opp1.Sub_Stage__c='Booked';
	opp1.Application_Date__c=system.today().addMonths(-3);
	opp1.UNQ_Customer__c='A1';
	opp1.UNQ_Vendor__c='A1';
	opp1.UNQ_Opportunity__c='A1';
	opp1.Billing_Address_Preference__c = 'Enter new billing address';
	//oppList.add(opp1);
	insert opp1;

	Messaging.InboundEnvelope env = new Messaging.InboundEnvelope();
	Messaging.InboundEmail mail = new Messaging.InboundEmail();

	mail.Subject = 'Application Number :' +opp1.Application_Number__c;
	mail.fromname = 'Geetha';
	env.fromAddress = 'geetha.bharadwaj@dllgroup.com';
	mail.plainTextBody = 'Test';

	//below code is for Document attachments
	Messaging.InboundEmail.BinaryAttachment docattachments = new Messaging.InboundEmail.BinaryAttachment();
	docattachments.body = blob.valueOf('my attachment Document');
	docattachments.fileName = 'docfile.doc';
	docattachments.mimeTypeSubType = 'text/plain';
	mail.binaryAttachments = null;

	//below code is for Text attachments
	Messaging.InboundEmail.textAttachment txtAttachment = new Messaging.InboundEmail.textAttachment();
	txtAttachment.body = 'My text attachemnt body';
	txtAttachment.fileName = 'textfile.txt';
	txtAttachment.mimeTypeSubType = 'text/plain';
	mail.textAttachments = null;

	Test.startTest();
	EnrollRequestDocsIncoming enrollreq1 = new EnrollRequestDocsIncoming();
	enrollreq1.handleInboundEmail(mail, env);
	Test.stopTest();

}
public static testMethod void method5() {

	List<Opportunity> oppList = new List<Opportunity>();

	Account at =new Account();
	at.Name='Service';
	insert at;

	contact ct =new contact();
	ct.LastName='Niranjan';
	ct.AccountId=at.id;
	ct.Email='arry@gmil.com';
	insert ct;

	Opportunity opp1= new Opportunity();
	//opp1.application_number__c='A1';
	opp1.Type='Overline';
	opp1.Name='Service';
	opp1.StageName='Closed Won';
	opp1.Accountid=at.id;
	opp1.Contact__c=ct.id;
	opp1.CloseDate=system.today()+1;
	opp1.Amount=11.0;
	opp1.End_User__c=at.id;
	opp1.End_User_Company_Name__c = 'DANIEL INC.';
	opp1.Business_Unit1__c='Digital Imaging';
	opp1.Sub_Stage__c='Booked';
	opp1.Application_Date__c=system.today().addMonths(-3);
	opp1.UNQ_Customer__c='A1';
	opp1.UNQ_Vendor__c='A1';
	opp1.UNQ_Opportunity__c='A1';
	opp1.Billing_Address_Preference__c = 'Enter new billing address';
	//oppList.add(opp1);
	insert opp1;

	Messaging.InboundEnvelope env = new Messaging.InboundEnvelope();
	Messaging.InboundEmail mail = new Messaging.InboundEmail();

	mail.Subject = 'Application Number :' +opp1.Application_Number__c;
	mail.fromname = 'Geetha';
	env.fromAddress = 'geetha.bharadwaj@dllgroup.com';
	mail.plainTextBody = 'Test';

	//below code is for Document attachments
	Messaging.InboundEmail.BinaryAttachment docattachments = new Messaging.InboundEmail.BinaryAttachment();
	docattachments.body = blob.valueOf('my attachment Document');
	docattachments.fileName = 'docfile.doc';
	docattachments.mimeTypeSubType = 'text/plain';
	mail.binaryAttachments = new Messaging.inboundEmail.BinaryAttachment[] { docattachments };

	//below code is for Text attachments
	Messaging.InboundEmail.textAttachment txtAttachment = new Messaging.InboundEmail.textAttachment();
	txtAttachment.body = 'My text attachemnt body';
	txtAttachment.fileName = 'textfile.txt';
	txtAttachment.mimeTypeSubType = 'text/plain';
	mail.textAttachments = new Messaging.inboundEmail.TextAttachment[] { txtAttachment };

	Test.startTest();
	EnrollRequestDocsIncoming enrollreq1 = new EnrollRequestDocsIncoming();
	enrollreq1.handleInboundEmail(mail, env);
	Test.stopTest();

}
public static testMethod void method6() {

	List<Opportunity> oppList = new List<Opportunity>();

	Account at =new Account();
	at.Name='Service';
	insert at;

	contact ct =new contact();
	ct.LastName='Niranjan';
	ct.AccountId=at.id;
	ct.Email='arry@gmil.com';
	insert ct;

	Opportunity opp1= new Opportunity();
	opp1.application_number__c='A1';
	opp1.Type='Overline';
	opp1.Name='Service';
	opp1.StageName='Closed Won';
	opp1.Accountid=at.id;
	opp1.Contact__c=ct.id;
	opp1.CloseDate=system.today()+1;
	opp1.Amount=11.0;
	opp1.End_User__c=at.id;
	opp1.End_User_Company_Name__c = 'DANIEL INC.';
	opp1.Business_Unit1__c='Digital Imaging';
	opp1.Sub_Stage__c='Booked';
	opp1.Application_Date__c=system.today().addMonths(-3);
	opp1.UNQ_Customer__c='A1';
	opp1.UNQ_Vendor__c='A1';
	opp1.UNQ_Opportunity__c='A1';
	opp1.billing_address_preference__c = 'Enter new billing address';
	// opp1.partner_sales_Rep__c = 'rep1';

	insert opp1;

	Opportunity_Line_Item__c oli =  new Opportunity_Line_Item__c();
	oli.Name = 'oli1';
	oli.opportunity__c = opp1.id;
	oli.line_item_type__c = 'Asset';
	oli.planned_install_date__c = system.today();

	insert oli;


	Contact c1 = new Contact();
	c1.phone = '1234567891';
	c1.LastName = 'Billing Contact LN';
	c1.FirstName = 'Billing Contact FN';
	c1.MiddleName = 'Billing Contact MN';
	c1.Title = 'Mr';
	//c1.Email = 'test@gmail.com';
	c1.AccountId = at.id;
	insert c1;

	OpportunityContactRole ocr1 = new OpportunityContactRole();
	ocr1.ContactId = c1.id;
	ocr1.Role = 'Billing Contact';
	ocr1.OpportunityId = opp1.id;
	insert ocr1;

	Contact c2 = new Contact();
	c2.phone = '1234567891';
	c2.LastName = 'Signer LN';
	c2.FirstName = 'Signer FN';
	c2.MiddleName = 'Signer MN';
	c2.Title = 'Mr';
	c2.Email = 'test@gmail.com';
	c2.AccountId = at.id;
	insert c2;

	OpportunityContactRole ocr2 = new OpportunityContactRole();
	ocr2.ContactId = c2.id;
	ocr2.Role = 'Signer';
	ocr2.OpportunityId = opp1.id;
	insert ocr2;

	Contact c3 = new Contact();
	c3.phone = '1234567891';
	c3.LastName = 'Reviewer LN';
	c3.FirstName = 'Reviewer FN';
	c3.MiddleName = 'Reviewer MN';
	c3.Title = 'Mr';
	c3.Email = 'test@gmail.com';
	c3.AccountId = at.id;
	insert c3;

	OpportunityContactRole ocr3 = new OpportunityContactRole();
	ocr3.ContactId = c3.id;
	ocr3.Role = 'Reviewer';
	ocr3.OpportunityId = opp1.id;
	insert ocr3;


	Messaging.InboundEnvelope env = new Messaging.InboundEnvelope();
	Messaging.InboundEmail mail = new Messaging.InboundEmail();

	mail.Subject = 'Application Number :' +opp1.Application_Number__c;
	mail.fromname = 'Geetha';
	env.fromAddress = 'geetha.bharadwaj@dllgroup.com';
	mail.plainTextBody = 'Test';

	//below code is for Document attachments
	Messaging.InboundEmail.BinaryAttachment docattachments = new Messaging.InboundEmail.BinaryAttachment();
	docattachments.body = blob.valueOf('my attachment Document');
	docattachments.fileName = 'docfile.doc';
	docattachments.mimeTypeSubType = 'text/plain';
	mail.binaryAttachments = new Messaging.inboundEmail.BinaryAttachment[] { docattachments };

	//below code is for Text attachments
	Messaging.InboundEmail.textAttachment txtAttachment = new Messaging.InboundEmail.textAttachment();
	txtAttachment.body = 'My text attachemnt body';
	txtAttachment.fileName = 'textfile.txt';
	txtAttachment.mimeTypeSubType = 'text/plain';
	mail.textAttachments = new Messaging.inboundEmail.TextAttachment[] { txtAttachment };


	Test.startTest();
	EnrollRequestDocsIncoming enrollreq = new EnrollRequestDocsIncoming();
	//enrollreq.handleInboundEmail(mail, env);
	EnrollRequestDocsIncoming.sendEmailforOpportunity(opp1.id);
	Test.stopTest();

}

}