force-app/main/default/objects/Opportunity/fields/Application_Approval_Date__c.field-meta.xml
<CustomField>
    <fullName>Application_Approval_Date__c</fullName>
    <description>This field shows the date/time when an Opportunity has been credit scored.</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Credit Decision Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Application_Date__c.field-meta.xml
<CustomField>
    <fullName>Application_Date__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>This is the date the application is first entered in the source system.</inlineHelpText>
    <label>Application Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Application_Number__c.field-meta.xml
<CustomField>
    <fullName>Application_Number__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <label>Application Number</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Business_Unit__c.field-meta.xml
<CustomField>
    <fullName>Business_Unit__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Relates an Opportunity to the DLL Business Unit servicing the sales deal. Populated via automation.</description>
    <label>Program Business Unit</label>
    <referenceTo>Business_Unit__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Business_Unit_Description__c.field-meta.xml
<CustomField>
    <fullName>Business_Unit_Description__c</fullName>
    <description>Captures the name of the Opportunity&apos;s related Business_Unit__c record as a text value. Used in Sharing Rules to permit sharing by Business Unit. Required because sharing rules cannot be written leveraging Lookup field values (i.e. Business_Unit__c). Populated by Apex code.</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Business Unit Description</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Contract__c.field-meta.xml
<CustomField>
    <fullName>Contract__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Relates an Opportunity to its Contract. Lookup populated via Apex code.</description>
    <label>Contract</label>
    <referenceTo>Contract__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Customer_Code__c.field-meta.xml
<CustomField>
    <fullName>Customer_Code__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Customer Code</label>
    <referenceTo>System_ID__c</referenceTo>
    <relationshipLabel>Opportunities (Customer Code)</relationshipLabel>
    <relationshipName>Opportunities1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/End_User__c.field-meta.xml
<CustomField>
    <fullName>End_User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Use this field to look up an existing Customer</inlineHelpText>
    <label>End User Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Opportunities (End User)</relationshipLabel>
    <relationshipName>Opportunities_End_User</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/End_User_Company_Name__c.field-meta.xml
<CustomField>
    <fullName>End_User_Company_Name__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Use this field when the customer does not exist in Salesforce</inlineHelpText>
    <label>End User Name (Text)</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/End_User_Phone__c.field-meta.xml
<CustomField>
    <fullName>End_User_Phone__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>End User Phone</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Existing_Match__c.field-meta.xml
<CustomField>
    <fullName>Existing_Match__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Existing Match</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Funded_Date__c.field-meta.xml
<CustomField>
    <fullName>Funded_Date__c</fullName>
    <description>Fed from data source.  Meant to drive the close date if populated</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Funded Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Legal_Entity_Description__c.field-meta.xml
<CustomField>
    <fullName>Legal_Entity_Description__c</fullName>
    <description>Captures the name of the DLL Legal Entity that is the ultimate parent to the operating sales Business Units managing the Opportunity as a text value. Used in Sharing Rules to permit sharing of Opportunities with Users working within the same Legal Entity. Populated by Apex code.</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Legal Entity Description</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Program__c.field-meta.xml
<CustomField>
    <fullName>Program__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Relates an Opportunity to its Program. The Opportunity&apos;s UNQ_Vendor_Program__c value is used to fetch the corresponding Program record by this external ID common to both objects. Populated by Apex code.</description>
    <label>Program</label>
    <referenceTo>Program__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Purchase_Option__c.field-meta.xml
<CustomField>
    <fullName>Purchase_Option__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Purchase Option</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Region_Description__c.field-meta.xml
<CustomField>
    <fullName>Region_Description__c</fullName>
    <description>Captures the name of the Opportunity&apos;s related Region_Relationship__c record as a text value. Used in Sharing Rules to permit sharing by Region. Required because sharing rules cannot be written leveraging Lookup field values (i.e. Region_Relationship__c). Populated by Apex code.</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Region Description</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Region_Relationship__c.field-meta.xml
<CustomField>
    <fullName>Region_Relationship__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Relates an Opportunity to its Region. Populated via automation.</description>
    <label>Region</label>
    <referenceTo>Region__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Risk_Grade__c.field-meta.xml
<CustomField>
    <fullName>Risk_Grade__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Risk Grade</label>
    <length>3</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Sales_Rep_ID_2__c.field-meta.xml
<CustomField>
    <fullName>Sales_Rep_ID_2__c</fullName>
    <description>Captures the unique identifier for the Sales Rep 2 individual assigned to an Opportunity. Set via integration. Used to query Salesforce for the User record corresponding to this individual. Related to Opportunity Apex function for Opportunity Owner and Opportunity Team Member insertion.</description>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <label>Sales Rep ID 2</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Sales_Rep_ID__c.field-meta.xml
<CustomField>
    <fullName>Sales_Rep_ID__c</fullName>
    <description>External ID for Sales Rep</description>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <label>Sales Rep ID</label>
    <length>125</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Sales_Rep_Name_2__c.field-meta.xml
<CustomField>
    <fullName>Sales_Rep_Name_2__c</fullName>
    <description>Captures the literal name of the Sales Rep 2 individual assigned to an Opportunity. Set via integration. Used in conjunction with the Sales Rep ID 2 field value to query Salesforce for the User record corresponding to this named individual. Related to Opportunity Apex function for Opportunity Owner and Opportunity Team Member insertion.</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Sales Rep Name 2</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Sales_Rep_Name__c.field-meta.xml
<CustomField>
    <fullName>Sales_Rep_Name__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Sales Rep Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Source_System__c.field-meta.xml
<CustomField>
    <fullName>Source_System__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Source System</label>
    <length>125</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Sub_Stage__c.field-meta.xml
<CustomField>
    <fullName>Sub_Stage__c</fullName>
    <description>Opportunity sub stages to be used by each BU</description>
    <label>Sub-Stage</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>StageName</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Warm Leads Identified</fullName>
            </value>
            <value>
                <fullName>On Hold</fullName>
            </value>
            <value>
                <fullName>Prospect</fullName>
            </value>
            <value>
                <fullName>Customer Meeting</fullName>
            </value>
            <value>
                <fullName>Executive Endorsement</fullName>
            </value>
            <value>
                <fullName>Nondisclosure Agreement Executed</fullName>
            </value>
            <value>
                <fullName>Required Functional Approvals Complete (Table 1)</fullName>
            </value>
            <value>
                <fullName>Workshop Hosted</fullName>
            </value>
            <value>
                <fullName>Principles Document/Term Sheet Drafted</fullName>
            </value>
            <value>
                <fullName>Required Functional Approvals Complete (Table 2)</fullName>
            </value>
            <value>
                <fullName>Principles Document/Term Sheet Signed</fullName>
            </value>
            <value>
                <fullName>Program Fact Sheet</fullName>
            </value>
            <value>
                <fullName>Development of Offer</fullName>
            </value>
            <value>
                <fullName>Vendor Risk Application</fullName>
            </value>
            <value>
                <fullName>Determine Risk Acceptance Criteria</fullName>
            </value>
            <value>
                <fullName>ABC Assessment</fullName>
            </value>
            <value>
                <fullName>Remarketing Arrangement</fullName>
            </value>
            <value>
                <fullName>Profit &amp; Loss Calculation</fullName>
            </value>
            <value>
                <fullName>Program Agreement Under Review</fullName>
            </value>
            <value>
                <fullName>DLL Selected</fullName>
            </value>
            <value>
                <fullName>Required Functional Approvals Complete (Table 3)</fullName>
            </value>
            <value>
                <fullName>Local Due Diligence &amp; Approval Committee</fullName>
            </value>
            <value>
                <fullName>Global Credit Committee Approval</fullName>
            </value>
            <value>
                <fullName>Determine Vendor Reporting Requirements</fullName>
            </value>
            <value>
                <fullName>Create Rollout Plan (Global)</fullName>
            </value>
            <value>
                <fullName>Implementation Plan (Local)</fullName>
            </value>
            <value>
                <fullName>Agreement Executed</fullName>
            </value>
            <value>
                <fullName>Assigned Local Implementation</fullName>
            </value>
            <value>
                <fullName>MVP Implemented</fullName>
            </value>
            <value>
                <fullName>Quote Draft</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/UNQ_Customer__c.field-meta.xml
<CustomField>
    <fullName>UNQ_Customer__c</fullName>
    <description>UNQ Customer ID from external system</description>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <label>UNQ Customer</label>
    <length>125</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/UNQ_Opportunity__c.field-meta.xml
<CustomField>
    <fullName>UNQ_Opportunity__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <label>UNQ Opportunity</label>
    <length>125</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Opportunity/fields/UNQ_Program__c.field-meta.xml
<CustomField>
    <fullName>UNQ_Program__c</fullName>
    <description>Unique ID for the Opportunity&apos;s Program. Set via integration.</description>
    <encryptionScheme>None</encryptionScheme>
    <label>UNQ Program</label>
    <length>125</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/UNQ_Vendor__c.field-meta.xml
<CustomField>
    <fullName>UNQ_Vendor__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>UNQ_Vendor</label>
    <length>125</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Vendor_Program__c.field-meta.xml
<CustomField>
    <fullName>Vendor_Program__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Vendor Program</label>
    <referenceTo>Vendor_Program__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/OpportunityMatchUpdateBatch.cls
/**
 * Created by samuelmeyers on 12/31/18.
 */

global class OpportunityMatchUpdateBatch implements Database.Batchable<sObject>{

    global final String query;

    global OpportunityMatchUpdateBatch(String q){
        this.query = q;
    } 

    global Database.QueryLocator start(Database.BatchableContext BC){
        return Database.getQueryLocator(this.query);
    }

    global void execute(Database.BatchableContext BC, List<sObject> scope){
        if(scope != null && scope.size() > 0){
            List<Opportunity> oppsWithMatches = (List<Opportunity>) scope;
            List<Opportunity> oppsToDelete = new List<Opportunity>();
            Map<Id, Opportunity> matches = new Map<Id, Opportunity>();

            for(Opportunity opp : oppsWithMatches){
                if(opp.Existing_Match__c != null){
                    if(!opp.Existing_Match__r.isDeleted){
                        Opportunity match = new Opportunity();
                        match.Id = opp.Existing_Match__c;
                        match.AccountId = opp.AccountId;
                        match.End_User__c = opp.End_User__c;
                        match.Sales_Rep_ID__c = opp.Sales_Rep_ID__c;
                        match.Sales_Rep_Name__c = opp.Sales_Rep_Name__c;
                        match.Amount = opp.Amount;
                        match.UNQ_Opportunity__c = opp.UNQ_Opportunity__c;
                        match.Application_Date__c = opp.Application_Date__c;
                        //match.Vendor_Program__c = opp.Vendor_Program__c;
                        match.Risk_Grade__c = opp.Risk_Grade__c;
                        match.StageName = opp.StageName;
                        match.Purchase_Option__c = opp.Purchase_Option__c;
                        match.Source_System__c = opp.Source_System__c;
                        match.Application_Approval_Date__c = opp.Application_Approval_Date__c;
                        match.Funded_Date__c = opp.Funded_Date__c;
                        //match.End_User_Phone__c = opp.End_User_Phone__c;
                        //PBI:446238:Update OpportunityMatchUpdateBatch to correct field mapping:Geetha
                        match.Sub_Stage__c = opp.Sub_Stage__c;
                        match.Program__c = opp.Program__c;
                        //PBI:507338: New fields added to update existing manual opp
                        match.UNQ_Customer__c = opp.UNQ_Customer__c;
                        match.UNQ_Program__c = opp.UNQ_Program__c;
                        match.Business_Unit__c = opp.Business_Unit__c;
                        match.Application_Number__c = opp.Application_Number__c; 
                        match.Business_Unit_Description__c = opp.Business_Unit_Description__c; 
                        match.CloseDate = opp.CloseDate;
                        match.Contract__c = opp.Contract__c;
                        match.Customer_Code__c = opp.Customer_Code__c; 
                        match.End_User_Company_Name__c = opp.End_User_Company_Name__c; 
                        match.Legal_Entity_Description__c =  opp.Legal_Entity_Description__c;
                        match.Region_Relationship__c = opp.Region_Relationship__c; 
                        match.Region_Description__c = opp.Region_Description__c;
                        match.Sales_Rep_ID_2__c = opp.Sales_Rep_ID_2__c;
                        match.Sales_Rep_Name_2__c = opp.Sales_Rep_Name_2__c; 
                        match.UNQ_Vendor__c = opp.UNQ_Vendor__c;
                        match.Vendor_ID__c = opp.Vendor_ID__c;
                        
                        matches.put(match.Id, match);
                        oppsToDelete.add(opp);
                    }else{
                        opp.Existing_Match__c = null;
                        matches.put(opp.Id, opp);
                    }
                }
            }
            //Flipped the logic to delete first and then update 
            //PBI:507338:Error in Opportunity Match Update Batch - Merge Opportunity Batch Failed - Root Cause UNQ_Opportunity is Unique field now
           
            if(oppsToDelete.size() > 0){
                delete oppsToDelete;
            }
            
            if(matches.size() > 0){
                update matches.values();
            }
        }
    }

    global void finish(Database.BatchableContext BC){
        System.debug('Matching Opportunities Consolidated');
    }
}