force-app/main/default/objects/Opportunity/fields/Business_Unit1__c.field-meta.xml
<CustomField>
    <fullName>Business_Unit1__c</fullName>
    <defaultValue>$User.Business_Unit_TEXT__c</defaultValue>
    <label>Opportunity Business Unit</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Advanced Solutions</fullName>
            </value>
            <value>
                <fullName>Clean Technology</fullName>
            </value>
            <value>
                <fullName>Commercial Finance</fullName>
            </value>
            <value>
                <fullName>Construction, Transportation &amp; Infrastructure (CTI)</fullName>
            </value>
            <value>
                <fullName>Food &amp; Agriculture (F&amp;A)</fullName>
            </value>
            <value>
                <fullName>Golf and Turf (G&amp;T)</fullName>
            </value>
            <value>
                <fullName>Healthcare</fullName>
            </value>
            <value>
                <fullName>Office Equipment (OE)</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Pay Per Use</fullName>
            </value>
            <value>
                <fullName>Public Finance</fullName>
            </value>
            <value>
                <fullName>Technology Solutions</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Business_Unit__c.field-meta.xml
<CustomField>
    <fullName>Business_Unit__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Relates an Opportunity to the DLL Business Unit servicing the sales deal. Populated via automation.</description>
    <label>Program Business Unit</label>
    <referenceTo>Business_Unit__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/End_User__c.field-meta.xml
<CustomField>
    <fullName>End_User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Use this field to look up an existing Customer</inlineHelpText>
    <label>End User Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Opportunities (End User)</relationshipLabel>
    <relationshipName>Opportunities_End_User</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/AccountTeamMemberScheduler.cls
/**
   *  @description A scheduler for both account and opportunity records that looks
   *  will look at the last 24 months of prospect accounts to find users to add to
   *  account teams, and for all time for opportunities with owners that are not apart
   *  of the end user and vendor account teams
   *  @author      Newton Sun, Traction on Demand
   *  @date        2020-04-02
 */
global class AccountTeamMemberScheduler implements Schedulable {
    global void execute(SchedulableContext sc) {
        RecordType prospectRecordType= [SELECT Name, Id FROM RecordType WHERE SobjectType='Account' AND Name='Prospect'];
        String accQuery = 'SELECT ' +
                'CreatedById, ' +
                'Id, ' +
                'Business_Unit__c ' +
                'FROM Account ' +
                'WHERE ' +
                'RecordTypeId = ' + '\'' + prospectRecordType.Id + '\'' +
                ' AND (CreatedDate = Last_N_Months:24 OR CreatedDate = THIS_MONTH)';
        AccountAccountTeamMemberBatch aub = new AccountAccountTeamMemberBatch(accQuery);
        Database.executeBatch(aub);
		/*
		 * Commented as per this task #368892
        String oppQuery = 'SELECT ' +
                'Id, ' +
                'End_User__c, ' +
                'AccountId, ' +
                'OwnerId, ' +
                'Business_Unit1__c ' +
                'FROM Opportunity ' +
                'WHERE ' +
                'CreatedDate < THIS_MONTH';

        OpportunityAccountTeamMemberBatch oatmb = new OpportunityAccountTeamMemberBatch(oppQuery);
        Database.executeBatch(oatmb);
		*/
    }
}