force-app/main/default/objects/Opportunity/fields/Business_Unit1__c.field-meta.xml
<CustomField>
    <fullName>Business_Unit1__c</fullName>
    <defaultValue>$User.Business_Unit_TEXT__c</defaultValue>
    <label>Opportunity Business Unit</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Advanced Solutions</fullName>
            </value>
            <value>
                <fullName>Clean Technology</fullName>
            </value>
            <value>
                <fullName>Commercial Finance</fullName>
            </value>
            <value>
                <fullName>Construction, Transportation &amp; Infrastructure (CTI)</fullName>
            </value>
            <value>
                <fullName>Food &amp; Agriculture (F&amp;A)</fullName>
            </value>
            <value>
                <fullName>Golf and Turf (G&amp;T)</fullName>
            </value>
            <value>
                <fullName>Healthcare</fullName>
            </value>
            <value>
                <fullName>Office Equipment (OE)</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Pay Per Use</fullName>
            </value>
            <value>
                <fullName>Public Finance</fullName>
            </value>
            <value>
                <fullName>Technology Solutions</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Business_Unit__c.field-meta.xml
<CustomField>
    <fullName>Business_Unit__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Relates an Opportunity to the DLL Business Unit servicing the sales deal. Populated via automation.</description>
    <label>Program Business Unit</label>
    <referenceTo>Business_Unit__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Commercial_Finance__c.field-meta.xml
<CustomField>
    <fullName>Commercial_Finance__c</fullName>
    <label>Commercial Finance</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>No</fullName>
            </value>
            <value>
                <fullName>Yes: Indirect - Tier 1</fullName>
            </value>
            <value>
                <fullName>Yes: Direct - Tier 1</fullName>
            </value>
            <value>
                <fullName>Yes: Direct - Tier 2</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Vendor Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/End_User__c.field-meta.xml
<CustomField>
    <fullName>End_User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Use this field to look up an existing Customer</inlineHelpText>
    <label>End User Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Opportunities (End User)</relationshipLabel>
    <relationshipName>Opportunities_End_User</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/End_User_Phone__c.field-meta.xml
<CustomField>
    <fullName>End_User_Phone__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>End User Phone</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Legal_Entity_Description__c.field-meta.xml
<CustomField>
    <fullName>Legal_Entity_Description__c</fullName>
    <description>Captures the name of the DLL Legal Entity that is the ultimate parent to the operating sales Business Units managing the Opportunity as a text value. Used in Sharing Rules to permit sharing of Opportunities with Users working within the same Legal Entity. Populated by Apex code.</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Legal Entity Description</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Program__c.field-meta.xml
<CustomField>
    <fullName>Program__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Relates an Opportunity to its Program. The Opportunity&apos;s UNQ_Vendor_Program__c value is used to fetch the corresponding Program record by this external ID common to both objects. Populated by Apex code.</description>
    <label>Program</label>
    <referenceTo>Program__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Sub_Stage__c.field-meta.xml
<CustomField>
    <fullName>Sub_Stage__c</fullName>
    <description>Opportunity sub stages to be used by each BU</description>
    <label>Sub-Stage</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>StageName</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Warm Leads Identified</fullName>
            </value>
            <value>
                <fullName>On Hold</fullName>
            </value>
            <value>
                <fullName>Prospect</fullName>
            </value>
            <value>
                <fullName>Customer Meeting</fullName>
            </value>
            <value>
                <fullName>Executive Endorsement</fullName>
            </value>
            <value>
                <fullName>Nondisclosure Agreement Executed</fullName>
            </value>
            <value>
                <fullName>Required Functional Approvals Complete (Table 1)</fullName>
            </value>
            <value>
                <fullName>Workshop Hosted</fullName>
            </value>
            <value>
                <fullName>Principles Document/Term Sheet Drafted</fullName>
            </value>
            <value>
                <fullName>Required Functional Approvals Complete (Table 2)</fullName>
            </value>
            <value>
                <fullName>Principles Document/Term Sheet Signed</fullName>
            </value>
            <value>
                <fullName>Program Fact Sheet</fullName>
            </value>
            <value>
                <fullName>Development of Offer</fullName>
            </value>
            <value>
                <fullName>Vendor Risk Application</fullName>
            </value>
            <value>
                <fullName>Determine Risk Acceptance Criteria</fullName>
            </value>
            <value>
                <fullName>ABC Assessment</fullName>
            </value>
            <value>
                <fullName>Remarketing Arrangement</fullName>
            </value>
            <value>
                <fullName>Profit &amp; Loss Calculation</fullName>
            </value>
            <value>
                <fullName>Program Agreement Under Review</fullName>
            </value>
            <value>
                <fullName>DLL Selected</fullName>
            </value>
            <value>
                <fullName>Required Functional Approvals Complete (Table 3)</fullName>
            </value>
            <value>
                <fullName>Local Due Diligence &amp; Approval Committee</fullName>
            </value>
            <value>
                <fullName>Global Credit Committee Approval</fullName>
            </value>
            <value>
                <fullName>Determine Vendor Reporting Requirements</fullName>
            </value>
            <value>
                <fullName>Create Rollout Plan (Global)</fullName>
            </value>
            <value>
                <fullName>Implementation Plan (Local)</fullName>
            </value>
            <value>
                <fullName>Agreement Executed</fullName>
            </value>
            <value>
                <fullName>Assigned Local Implementation</fullName>
            </value>
            <value>
                <fullName>MVP Implemented</fullName>
            </value>
            <value>
                <fullName>Quote Draft</fullName>
            </value>
            <value>
                <fullName>Qualifying</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/UNQ_Customer__c.field-meta.xml
<CustomField>
    <fullName>UNQ_Customer__c</fullName>
    <description>UNQ Customer ID from external system</description>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <label>UNQ Customer</label>
    <length>125</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/UNQ_Opportunity__c.field-meta.xml
<CustomField>
    <fullName>UNQ_Opportunity__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <label>UNQ Opportunity</label>
    <length>125</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Opportunity/fields/UNQ_Program__c.field-meta.xml
<CustomField>
    <fullName>UNQ_Program__c</fullName>
    <description>Unique ID for the Opportunity&apos;s Program. Set via integration.</description>
    <encryptionScheme>None</encryptionScheme>
    <label>UNQ Program</label>
    <length>125</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/UNQ_Vendor__c.field-meta.xml
<CustomField>
    <fullName>UNQ_Vendor__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>UNQ_Vendor</label>
    <length>125</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/UNQ_Vendor_Program__c.field-meta.xml
<CustomField>
    <fullName>UNQ_Vendor_Program__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>UNQ Vendor Program</label>
    <length>125</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/OpportunityTeamMemberTriggerTest.cls
/*PBI:665017:Opportunity Team - End User Visibility Enable: DLL on Demand
 * Opportunity access automaticall shared. Enduser account is apex shared.
 * version1: Geetha Bharadwaj
 * Commenting out the logic for Apex Sharing for DLL on Demand
 */
@isTest
public class OpportunityTeamMemberTriggerTest {
   /* @isTest static void oppTeamMem_M1(){
         User x = new User(
            ProfileId = [SELECT Id FROM Profile WHERE Name = 'System Administrator'].Id,
            LastName = 'last2',
            Email = 'test@test.com',
            Username = 'test@test.com' + System.currentTimeMillis(),
            CompanyName = 'TEST',
            Title = 'title',
            Alias = 'alias',
            TimeZoneSidKey = 'America/Los_Angeles',
            EmailEncodingKey = 'UTF-8',
            LanguageLocaleKey = 'en_US',
            LocaleSidKey = 'en_US',
            Business_Unit__c = 'Commercial Finance',
            isActive = true,
            Legal_Entity_Description__c = 'DLL'
        );
        insert x;
        system.debug('x= ' +x);
        Id RecordTypeIdAccountEndUser = Schema.SObjectType.Account.getRecordTypeInfosByName().get('End User').getRecordTypeId();
        Id RecordTypeIdAccountVendor = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Vendor').getRecordTypeId();
        Id RecordTypeIdAccountProspect = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Prospect').getRecordTypeId();
       
        Account acc =new Account();
        acc.Name='test';
        acc.Technology_Solutions__c=false;
        acc.CleanTech__c=false;
        acc.Commercial_Finance__c=false;
        acc.BillingStreet = '3321 LEGION RD';
        acc.BillingCity = 'HOPE MILLS5';
        acc.BillingPostalCode = '28348-1652';
        acc.BillingState = 'North Carolina2';
        acc.BillingCountry = 'US';   
        insert acc;  
        
        System.assertNotEquals(null, acc.Id);
        
        Account parentEnduser =new Account();
        parentEnduser.Name='testparent end user';
        parentEnduser.RecordTypeId=RecordTypeIdAccountEndUser;
        parentEnduser.BillingStreet = 'Am Tierpark 16';
        parentEnduser.BillingCity = 'Cologne';
        parentEnduser.BillingPostalCode = '54321';
        parentEnduser.BillingState = 'Nordrhein-Westfalen';
        parentEnduser.BillingCountry = 'Germany';
        insert parentEnduser;
        
        System.assertNotEquals(null, parentEnduser.Id);
        
        Account at =new Account();
        at.Name='Service';
        at.RecordTypeId=RecordTypeIdAccountEndUser;
        at.ParentId=parentEnduser.Id;
        at.Technology_Solutions__c=false;
        at.BillingStreet = 'Am Tierpark 16';
        at.BillingCity = 'Cologne';
        at.BillingPostalCode = '54321';
        at.BillingState = 'Nordrhein-Westfalen';
        at.BillingCountry = 'Germany';
        insert at;
        
        System.assertNotEquals(null, at.Id);
        System.assertEquals(at.ParentId,parentEnduser.Id);
        
        Contact ct =new Contact();
        ct.LastName='Niranjan';
        ct.AccountId=at.Id;
        ct.Email='arry@gmil.com';
        insert ct;
        
        System.assertNotEquals(null, ct.Id);
        System.assertEquals(ct.AccountId,at.Id);
        
        System_ID__c sys =new System_ID__c();
        sys.System_Name__c='test';
        sys.UNQ_Vendor__c='1234';
        sys.UNQ_Customer__c='123';
        sys.Phone__c='7889057582';
        sys.Account__c=at.Id;
        insert sys;
        
        System.assertNotEquals(null, sys.Id);
        System.assertEquals(sys.Account__c,at.Id);

        
        Program__c program =new Program__c();
        program.Program_Code__c='TEST';
        program.Partner__c=at.Id;
        program.UNQ_Program__c = 'TEST';
        insert program;
        //Below code added by Geetha Bharadwaj - DLL
        Program__c program2 =new Program__c();
        program2.Program_Code__c='TEST1';
        program2.Partner__c=at.Id;
        program2.UNQ_Program__c = 'TEST1';
        insert program2;
        
        
        System.assertNotEquals(null, program.Id);
        System.assertEquals(program.Partner__c,at.Id);
        
        Account_Account_Relationship__c aar=new Account_Account_Relationship__c();
        aar.Account_1__c=acc.Id;
        aar.Account_2__c=at.Id;
        aar.Role__c='End User';        
        insert aar;
        Account_Account_Relationship__c aar2=new Account_Account_Relationship__c();
        aar2.Account_1__c=at.Id;
        aar2.Account_2__c=acc.Id;
        aar2.Role__c='Vendor';        
        insert aar2;
        System.assertNotEquals(null, aar.Id);
        System.assertNotEquals(null, aar2.Id);
        
        
        Opportunity opp= new Opportunity();
        opp.Type='New';
        opp.Name='Service';
        opp.StageName='On Hold';
        opp.AccountId=acc.Id;
        opp.Contact__c=ct.Id;
        opp.CloseDate=System.today()+1;
        opp.Amount=22.0;
        opp.End_User__c=at.Id;
        opp.Business_Unit1__c='Digital Imaging';
        opp.UNQ_Customer__c='123';
        //opp.UNQ_Vendor_Program__c='TEST';
        opp.UNQ_Program__c=program.UNQ_Program__c;
        opp.UNQ_Vendor__c='1234';
        opp.UNQ_Opportunity__c='12345T';
        opp.Business_Unit1__c='CleanTech';
        opp.End_User_Phone__c='123456';
        opp.Program__c = program.Id;
        opp.Sub_Stage__c = 'Qualifying';
        opp.StageName = 'Qualifying';
        insert opp; 
        
        //insert Opp team member - Test Sharing
        
        OpportunityTeamMember oppTeamMem = new OpportunityTeamMember();
        oppTeamMem.OpportunityId = opp.Id;
        oppTeamMem.OpportunityAccessLevel = 'read';
        oppTeamMem.TeamMemberRole = 'Partner Admin';
        oppTeamMem.UserId = x.Id;
        insert oppTeamMem;
         
       
        
       
        List<OpportunityShare> oppshareList = [SELECT Id,OpportunityAccessLevel,OpportunityId,RowCause,UserOrGroup.FirstName 
                                               FROM OpportunityShare 
                                               where OpportunityId = :opp.Id
                                               and RowCause = 'Team'
                                               and OpportunityAccessLevel = 'read' ];
        system.debug('oppshareList ' +oppshareList);
        system.assertEquals(1, oppshareList.size());
        
        //delete OppteamMember
        
        List<OpportunityTeamMember> opptmlist = [select id from OpportunityTeamMember 
                                                 where OpportunityId = :opp.Id
                                                 and  UserId = :x.Id];
        
        delete opptmlist;
        
        List<OpportunityShare> oppshareList1 = [SELECT Id,OpportunityAccessLevel,OpportunityId,RowCause,UserOrGroup.FirstName 
                                               FROM OpportunityShare 
                                               where OpportunityId = :opp.Id
                                               and RowCause = 'Team'
                                               and OpportunityAccessLevel = 'read' ];
        
        system.assertEquals(0,oppshareList1.size());
        
    } */
}