force-app/main/default/objects/Opportunity/fields/Contract__c.field-meta.xml
<CustomField>
    <fullName>Contract__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Relates an Opportunity to its Contract. Lookup populated via Apex code.</description>
    <label>Contract</label>
    <referenceTo>Contract__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/End_User__c.field-meta.xml
<CustomField>
    <fullName>End_User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Use this field to look up an existing Customer</inlineHelpText>
    <label>End User Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Opportunities (End User)</relationshipLabel>
    <relationshipName>Opportunities_End_User</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity_Line_Item__c/Opportunity_Line_Item__c.object-meta.xml
<CustomObject>
    <description>Application line items are used in the DLL on Demand partner portal to represent assets and fees tracked during the credit application process. The standard object was not used as products and price books aren&apos;t used in the DoD portal currently.</description>
    <label>Opportunity Line Item</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Line Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Opportunity Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Opportunity_Line_Item__c/fields/Line_Item_Type__c.field-meta.xml
<CustomField>
    <fullName>Line_Item_Type__c</fullName>
    <businessOwnerGroup>North_America_Admins</businessOwnerGroup>
    <description>The type of line item used to indicate what the item is for and how to use it in calculations.</description>
    <inlineHelpText>The type of line item used to indicate what the item is for and how to use it in calculations.</inlineHelpText>
    <label>Line Item Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Asset</fullName>
            </value>
            <value>
                <fullName>Add-on</fullName>
            </value>
            <value>
                <fullName>Fee</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity_Line_Item__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <businessOwnerGroup>North_America_Admins</businessOwnerGroup>
    <description>The parent opportunity that the line item is for.</description>
    <inlineHelpText>The parent opportunity that the line item is for.</inlineHelpText>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipName>Application_Line_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Opportunity_Line_Item__c/fields/Planned_Install_City__c.field-meta.xml
<CustomField>
    <fullName>Planned_Install_City__c</fullName>
    <businessOwnerGroup>North_America_Admins</businessOwnerGroup>
    <description>The city the asset is expected to be delivered to.</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>The city the asset is expected to be delivered to.</inlineHelpText>
    <label>Planned Install City</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity_Line_Item__c/fields/Planned_Install_Date__c.field-meta.xml
<CustomField>
    <fullName>Planned_Install_Date__c</fullName>
    <businessOwnerGroup>North_America_Admins</businessOwnerGroup>
    <description>The date the asset is anticipated to be delivered to the customer&apos;s planned install address.</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>The date the asset is anticipated to be delivered to the customer&apos;s planned install address.</inlineHelpText>
    <label>Planned Install Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Opportunity_Line_Item__c/fields/Planned_Install_State__c.field-meta.xml
<CustomField>
    <fullName>Planned_Install_State__c</fullName>
    <businessOwnerGroup>North_America_Admins</businessOwnerGroup>
    <description>The state the asset is expected to be delivered to.</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>The state the asset is expected to be delivered to.</inlineHelpText>
    <label>Planned Install State</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity_Line_Item__c/fields/Planned_Install_Street__c.field-meta.xml
<CustomField>
    <fullName>Planned_Install_Street__c</fullName>
    <businessOwnerGroup>North_America_Admins</businessOwnerGroup>
    <description>The street address the asset is expected to be delivered to.</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>The street address the asset is expected to be delivered to.</inlineHelpText>
    <label>Planned Install Street</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity_Line_Item__c/fields/Planned_ZIP_Code__c.field-meta.xml
<CustomField>
    <fullName>Planned_ZIP_Code__c</fullName>
    <businessOwnerGroup>North_America_Admins</businessOwnerGroup>
    <description>The postal/zip code the asset is expected to be delivered to.</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>The postal/zip code the asset is expected to be delivered to.</inlineHelpText>
    <label>Planned ZIP Code</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/CustomerInstallAddresses.cls
/*
* CustomerInstallAddresses: Enables a user to query install addresses related to an end user customer.
* 2022-07-17: Created
*/
public without sharing class CustomerInstallAddresses {

    @AuraEnabled(cacheable=true)
    public static Map<String, String> getAddresses(Id oppId) {

        // Get the end user from the opportunity.
        Opportunity opp = [
            SELECT End_User__c
            FROM Opportunity
            WHERE Id = :oppId
            LIMIT 1
        ];

        // Then get the contracts related to that end user.
        List<Contract__c> contractList = [
            SELECT Id
            FROM Contract__c
            WHERE End_User__c = :opp.End_User__c
            LIMIT 1000
        ];

        // Then get the asset install addresses related to those contracts.
        List<Asset__c> assets = [
            SELECT Asset_City_Install_Address__c,
                Asset_Install_Address_Line_1__c,
                Asset_Install_Address_Line_2__c,
                Asset_Postal_Code_Install_Address__c,
                Asset_State_Install_Address__c
            FROM Asset__c
            WHERE Contract__c IN :contractList
            // ORDER BY Asset_State_Install_Address__c, Asset_City_Install_Address__c // The list gets sorted by street address below.
            LIMIT 1000
        ];

        // Loop through the assets and create a unique list of install addresses.
        List<String> setOfValues = new List<string>();
        for(Asset__c obj :assets) {
            string fullAddress = '';
            fullAddress = string.valueof(obj.Asset_Install_Address_Line_1__c) !=null ? fullAddress + string.valueof(obj.Asset_Install_Address_Line_1__c) : fullAddress;
            fullAddress = string.valueof(obj.Asset_Install_Address_Line_2__c) !=null ? fullAddress + ', ' + fullAddress+string.valueof(obj.Asset_Install_Address_Line_2__c) : fullAddress;
            fullAddress = string.valueof(obj.Asset_City_Install_Address__c) !=null ? fullAddress + ', ' + string.valueof(obj.Asset_City_Install_Address__c) : fullAddress;
            fullAddress = string.valueof(obj.Asset_State_Install_Address__c) !=null ? fullAddress + ', ' + string.valueof(obj.Asset_State_Install_Address__c) : fullAddress;
            fullAddress = string.valueof(obj.Asset_Postal_Code_Install_Address__c) != null ? fullAddress + ', ' + string.valueof(obj.Asset_Postal_Code_Install_Address__c) : fullAddress;
            if(fullAddress != ''){
                setOfValues.add(fullAddress);
            }
        }

        // Then merge in existing opportunity line addresses.
        List<Opportunity_Line_Item__c> oppLineItemList = [
            SELECT Planned_Install_City__c,
                Planned_Install_Date__c,
                Planned_Install_State__c,
                Planned_Install_Street__c,
                Planned_ZIP_Code__c
            FROM Opportunity_Line_Item__c
            WHERE Line_Item_Type__c = 'Asset'
            AND Opportunity__c = :oppId
            // ORDER BY Planned_Install_State__c, Planned_Install_City__c // The list gets sorted by street address below.
        ];

        // Loop through the assets and add to the list.
        for(Opportunity_Line_Item__c obj :oppLineItemList) {
            string fullAddress = '';

            // Break up the street address into two parts.
            if (obj.Planned_Install_Street__c != null) {

                fullAddress = obj.Planned_Install_Street__c;
                /*
                List<String> addressParts = obj.Planned_Install_Street__c.split(',');
                if (addressParts.size() == 1) {
                    fullAddress = addressParts[0];
                }else if (addressParts.size() == 2) {
                    fullAddress = addressParts[0] + ' ' + addressParts[1];
                }
                */
            }

            fullAddress = string.valueof(obj.Planned_Install_City__c) !=null ? fullAddress + ', ' + string.valueof(obj.Planned_Install_City__c) : fullAddress;
            fullAddress = string.valueof(obj.Planned_Install_State__c) !=null ? fullAddress + ', ' + string.valueof(obj.Planned_Install_State__c) : fullAddress;
            fullAddress = string.valueof(obj.Planned_ZIP_Code__c) != null ? fullAddress + ', ' + string.valueof(obj.Planned_ZIP_Code__c) : fullAddress;
            if(fullAddress != ''){
                setOfValues.add(fullAddress);
            }
        }

        // Turn the set into a map.
        Map<String, String> values = new Map<String, String>{};
        setOfValues.sort();
        for(string val :setOfValues) {
            values.put(val, val);
        }

        // Return the map of install values.
        return values;
    }
}