force-app/main/default/objects/Opportunity/fields/End_User__c.field-meta.xml
<CustomField>
    <fullName>End_User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Use this field to look up an existing Customer</inlineHelpText>
    <label>End User Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Opportunities (End User)</relationshipLabel>
    <relationshipName>Opportunities_End_User</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Sub_Stage__c.field-meta.xml
<CustomField>
    <fullName>Sub_Stage__c</fullName>
    <description>Opportunity sub stages to be used by each BU</description>
    <label>Sub-Stage</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>StageName</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Warm Leads Identified</fullName>
            </value>
            <value>
                <fullName>On Hold</fullName>
            </value>
            <value>
                <fullName>Prospect</fullName>
            </value>
            <value>
                <fullName>Customer Meeting</fullName>
            </value>
            <value>
                <fullName>Executive Endorsement</fullName>
            </value>
            <value>
                <fullName>Nondisclosure Agreement Executed</fullName>
            </value>
            <value>
                <fullName>Required Functional Approvals Complete (Table 1)</fullName>
            </value>
            <value>
                <fullName>Workshop Hosted</fullName>
            </value>
            <value>
                <fullName>Principles Document/Term Sheet Drafted</fullName>
            </value>
            <value>
                <fullName>Required Functional Approvals Complete (Table 2)</fullName>
            </value>
            <value>
                <fullName>Principles Document/Term Sheet Signed</fullName>
            </value>
            <value>
                <fullName>Program Fact Sheet</fullName>
            </value>
            <value>
                <fullName>Development of Offer</fullName>
            </value>
            <value>
                <fullName>Vendor Risk Application</fullName>
            </value>
            <value>
                <fullName>Determine Risk Acceptance Criteria</fullName>
            </value>
            <value>
                <fullName>ABC Assessment</fullName>
            </value>
            <value>
                <fullName>Remarketing Arrangement</fullName>
            </value>
            <value>
                <fullName>Profit &amp; Loss Calculation</fullName>
            </value>
            <value>
                <fullName>Program Agreement Under Review</fullName>
            </value>
            <value>
                <fullName>DLL Selected</fullName>
            </value>
            <value>
                <fullName>Required Functional Approvals Complete (Table 3)</fullName>
            </value>
            <value>
                <fullName>Local Due Diligence &amp; Approval Committee</fullName>
            </value>
            <value>
                <fullName>Global Credit Committee Approval</fullName>
            </value>
            <value>
                <fullName>Determine Vendor Reporting Requirements</fullName>
            </value>
            <value>
                <fullName>Create Rollout Plan (Global)</fullName>
            </value>
            <value>
                <fullName>Implementation Plan (Local)</fullName>
            </value>
            <value>
                <fullName>Agreement Executed</fullName>
            </value>
            <value>
                <fullName>Assigned Local Implementation</fullName>
            </value>
            <value>
                <fullName>MVP Implemented</fullName>
            </value>
            <value>
                <fullName>Quote Draft</fullName>
            </value>
            <value>
                <fullName>Calculation</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/TestOpportunityBuilder.cls
/**
 * Test class for creating Opportunity test data 
 * Version 1.0
 */
@isTest
public class TestOpportunityBuilder {

    private String name = 'Apple';
    private String type = 'New';
    private String stage = 'Quoting';
    private String subStage = 'Calculation';
    private Integer daysAfterToday = 365;
    private Date closeDate  = Date.today() + daysAfterToday;
    private Id accountId;
    private Id recordTypeId;
    private Id customerId;
    private String currencyIsoCode = 'SEK';
    private Integer amount;
    private Id standardPricebook;

    private Boolean insertRecord = false;

    public TestOpportunityBuilder withRecordType(String recordTypeDeveloperName){
        recordTypeId = Schema.SObjectType.Opportunity.getRecordTypeInfosByDeveloperName().get(recordTypeDeveloperName).getRecordTypeId();
        return this;
    }

    public TestOpportunityBuilder withName(String name) {
        this.name = name;
        return this;
    }

    public TestOpportunityBuilder withAccount(Id accountId) {
        this.accountId = accountId;
        return this;
    }

    public TestOpportunityBuilder withType(String type) {
        this.type = type;
        return this;
    }

    public TestOpportunityBuilder withStage(String stage) {
        this.stage = stage;
        return this;
    }

    public TestOpportunityBuilder withSubStage(String subStage) {
        this.subStage = subStage;
        return this;
    }

    public TestOpportunityBuilder withCloseDate(Date closeDate) {
		this.closeDate = closeDate;
		return this;
    }
    
    public TestOpportunityBuilder withEndUser(Id customerId) {
		this.customerId = customerId;
		return this;
    }
    
    public TestOpportunityBuilder withCurrencyIsoCode(String currencyIsoCode) {
		this.currencyIsoCode = currencyIsoCode;
		return this;
	}

    public TestOpportunityBuilder withAmount(Integer amount) {
		this.amount = amount;
		return this;
	}

    public TestOpportunityBuilder withStandardPricebook(Id standardPricebook) {
		this.standardPricebook = standardPricebook;
		return this;
	}

    public TestOpportunityBuilder insertRecord(Boolean insertRecord) {
        this.insertRecord = insertRecord;
        return this;
    }

    public Opportunity build(){

        Opportunity testOpportunity = new Opportunity(
            RecordTypeId = this.recordTypeId,
            Name = this.name,
            Type = this.type,
            StageName = this.stage,
            Sub_Stage__c = this.subStage,
            CloseDate = this.closeDate,
            AccountId = this.accountId,
            End_User__c = this.customerId,
            currencyIsoCode = this.currencyIsoCode,
            amount = this.amount,
            pricebook2id = this.standardPricebook
        );

        if(insertRecord) {
            insert testOpportunity;
        }

        return testOpportunity;
    }
}